### ISSUE TITLE
Book 4 Cover

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#10]
Here is the suggested cover.

- [ ] Do you like the colour? If not, perhaps a Google Hangout where I share my screen and we choose a colour together?

- [ ] Title - obviously this title won't work if we don't do any travelled sequences ... I was just trying to keep the title in the "spirit" of the other 3 books. I think we will only be able to decide the title once we have decided on the content. So just think of this as a place-marker for now.

![book4cover](https://cloud.githubusercontent.com/assets/15850667/22248900/ba2071e4-e20e-11e6-8bf6-85245bcbb7e4.jpg)

**Comment by rryman** [comment]
Once the book is completed, we may want to title it:
Stage Plans, Location Signs, and Travelled Sequences.

**Comment by rsryman** [comment]
Right, good point.

**Comment by rryman** [comment]
I have updated the cover. I worked on the image a bit to make our names appear whiter. I had to make the subtitle of the book a smaller font in order to fit it on one row. Hopefully the text will still be legible on the cover in the iBooks Store.
![book4cover](https://cloud.githubusercontent.com/assets/15850667/24778072/a3090dec-1af6-11e7-83be-5de410c63a06.jpg)

**Comment by rsryman** [comment]
Looks good!

PS, Jack's doctor told him to discontinue the antibiotic and come in for another blood and urine draw tomorrow morning.
