### ISSUE TITLE
Appendices

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook4#15]
**DONE**

See file uploaded to Dropbox: MoreAboutStagePlans.docx

I have word-smithed p. 22 Appendix. We should discuss using handwritten excerpts from Napoli or Realm.

**Comment by rryman** [comment]
I have added this new wording.

BTW, Liz said not to link to the Encyclopedia because there are still too many unknown about to whom and how it will be available.

I have it on my to do list to look for examples from Realm. I am not sure I ever used stage plans between two staves, but I will check.

**Comment by rryman** [comment]
Rhonda, I have been through _Realm_ and I am pretty sure I would have to rewrite the excerpts to use them as examples in our ebook. Perhaps it is worth waiting until you get home to see if you have better examples from Napoli that we could use that could just be scanned. The other option is to contact Liz and ask if we can use the example that RAD has on their website (see attached pdf).
[Benesh Movement Notation Score updated Nov2014.pdf](https://github.com/rryman/BeneshForBalletBook4/files/870247/Benesh.Movement.Notation.Score.updated.Nov2014.pdf)

**Comment by rsryman** [comment]
Whatever you prefer. If you can wait until late April I can check Napoli. Or you can go to my condo - Arthur has a key. The big black binder is in the bookshelf in the den.

**Comment by rryman** [comment]
Please see my suggested version on Page 36 of the newly uploaded iba file. It is best viewed on your iPad so you can see how the pdfs open. As you can see, I used two URLs just in case one of them ever changes ... hopefully they are stable links!

If you do not like this suggestion, I am more than happy to change it and to include examples from Napoli once you are back in Toronto and able to scan them and obtain permission to use them. I can always ask my friend, Janette, if she can connect us with Peter Schaffus as she was once married to him and had two children with him, so I suspect she is still in communication with him.

**Comment by rsryman** [comment]
What a great idea! Why duplicate resources (although as you say the links may change). Let's go with this for now. Suggested rewording: "To see how stage plans are used in a multi-stave score, go to the RAD Canada Benesh website or the the RAD UK Benesh website and scroll to pages 5-7."

**Comment by rryman** [comment]
"To see how stage plans are used in a multi-stave score, go to the RAD Canada Benesh website or the the RAD UK Benesh website and scroll to pages 5-7."

This wording is misleading ... the link takes you to a pdf on the website and then you scroll to pages 5-7 within the pdf. I am happy to reword it, but I don't want to change the meaning in the process.

**Comment by rsryman** [comment]
I suggested the change because I myself misread the directions. Is this any better: "To see how stage plans are used in a multi-stave score, go to the Benesh Movement score PDF on the RAD Canada Benesh website or the the RAD UK Benesh website and scroll to pages 5-7."

**Comment by rsryman** [comment]
As discussed by phone, here is a suggested note re p. 39: 
The placement of the horizontal tick just upstage or downstage of "**Middle**" is considered non-discernible because it strains visual perception, particularly on wing quarter and centre quarter location signs. While these placements are not discernible in isolation, they may be used in context.

**Comment by rryman** [comment]
Suggested changes ...
In the stage plan above there are gaps just upstage and downstage of “**Middle**” because the placement of the horizontal tick on these _location_ signs (particularly on _wing quarters_ and _centre quarters_) is not perceptible. While these horizontal placements are not discernible in isolation, they may be used in context.

**Comment by rsryman** [comment]
Yes, a better lead-in. What about: In the stage plan above there are gaps just upstage and downstage of “Middle” because this placement of the horizontal tick is difficult to perceive, particularly on wing quarter and centre quarter location signs. While these horizontal placements are not discernible in isolation, they may be used in context.

**Comment by rryman** [comment]
More About Location Terminology - Appendix page 37
Is the information on this page of any value? If not, I will delete the page and the link leading to it.
If so, please feel free to wordsmith it if needed.

**Comment by rsryman** [comment]
I find the info on p. 37 interesting and useful. We give historical tidbits so why not professional tips? I'll wordsmith when I get to that page, OK?

**Comment by rryman** [comment]
Sounds like a plan.
