### ISSUE TITLE
Content for Book 4

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#17]
**DONE - Updated Below**

Thinking out loud:
Benesh Basics 11 - all travel signs; then a Review Section.
Next Chapter - below stave information from Solo Seal examples, direction signs, travel signs, and stage plans?
Benesh Basics 12 - step, slide, jump lines, bourees, ad lib.
Next Chapter - putting them together in simple notated examples with in-stave and below-stave information.
Benesh Basics 13 - curved travel, brackets, etc.
Next Chapter - below stave information from Solo Seal examples of curved travel; and putting in-stave and below-stave information together with simple notated examples.
Next Chapter - Bournonville enchainements (this may mean having to introduce new sub-beats?).
You do realize that Sandy's notation uses very few location and travel signs? I could only see about 4 examples where there was any at all, and then only used sparingly.

**Comment by rryman** [comment]
We should include entrances and exits as well, once we have covered travel signs.

**Comment by rsryman** [comment]
Yes, these are important to introduce; some are needed in Caprice.

**Comment by rryman** [comment]
**Chapter 1 - About This Book**
1. About Stage Plans, Location, and Travel
2. How This Book is Organized
3. How to Navigate This Book

**Chapter 2 BB10:**
1. Basic Stage Plan
2. Location Signs
3. Location and In-Stave Information
4. Review of Location Signs

**Chapter 3 BB11:**
1. General Travel Signs
2. Travel Forward and Backward
3. Travel Sideways
4. Travel Diagonally
5. Review of Travel Signs

**Chapter 4 BB12:**
1. Entrances/exits
2. Brackets & curved travel
3. Music bar numbers?
4. RAD Solo Seal Caprice Example: series of stage plans with location and travel information below (as on p. 23); with relevant music bar numbers; with summarizing geometric travel pattern?; with top view animation if needed, key poses but no actual choreographed movements?
5. Review?

**Chapter 5 BB13:**
(Location signs are written below the stave in conjunction with direction faced and travel signs to show the floor plan of a sequence. The placement of this information in relation to the movement instructions recorded in the stave shows the timing of each manoeuvre.)
1. Locomotion lines
2. Ad lib dashes (walking, running, bourreeing, etc.)
3. Examples notated from pages 23, 25, 27, 29, and 32
4. Review?

**Chapter 6 Travelled Sequences?:**
1. Use the examples in GitHub Issue - Bournonville Enchainements #18 with added locations and travel signs where necessary. Notation and animations for each excerpt.
2. Review?

**Chapter 7 Appendix:**
1. Stage Plans and Multi-stave Scores
2. More About Location Terminology (to be moved to the introduction in Chapter 1?)
3. Interactive Stage Plans
4. Direction Signs and Room Numbering
5. Multi-dancer Scores
6. Likely RAD Terms for Locations
7. More Examples of Travel Diagonally

**Chapter 8 Sources:**
1. Italian Vocabulary
2. Russian Vocabulary
3. English Vocabulary
4. Electronic Media
5. Benesh Movement Notation
6. General

Chapter 9 About the Authors:**
1. Rhonda Ryman-Kane
2. Robyn Hughes Ryman
