### ISSUE TITLE
Bournonville Enchainements

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#18]
Bournonville has slim pickins' when it comes to the use of stage locations and travel signs. Here is one from the Saturday class. Do you think we could add a travel forward sign in the beginning?
![bournonvillesaturday](https://cloud.githubusercontent.com/assets/15850667/23950433/59d94e94-0961-11e7-9dfc-a77a28c98a10.jpg)

**Comment by rryman** [comment]
Friday Class - perhaps we could only do this with one dancer so we don't have to worry about explaining the reflection theory?
![bournonvillefriday](https://cloud.githubusercontent.com/assets/15850667/23950748/6ed511ba-0962-11e7-87e1-faab48ea8d41.jpg)
![bournonvillefriday2](https://cloud.githubusercontent.com/assets/15850667/23950752/70b667ea-0962-11e7-9617-277b4da60161.jpg)

**Comment by rryman** [comment]
Wednesday Class - the rest of this enchainement does not use stage locations. Maybe we could just use this excerpt and finish it in the attitude on the last repeat? Perhaps we could add a diagonal back travel sign in Bar 3, a forward travel sign in Bar 5, and an appropriate location sign in Bar 8?
![bournonvillewed](https://cloud.githubusercontent.com/assets/15850667/23951081/7ddd2a66-0963-11e7-9e0b-e3f199940233.jpg)

**Comment by rryman** [comment]
Monday Class - the rest of this enchainement does not use stage locations. Maybe we could just use the first 8 bars? Good example of travel in a circular path? Maybe we could add a couple of locations and some brackets around the circular travel sign?
![bournonvillemon](https://cloud.githubusercontent.com/assets/15850667/23951304/170c34a2-0964-11e7-8e11-1a350ee0f763.jpg)

**Comment by rryman** [comment]
I went through the whole Bournonville book and these are the only places I found location signs. Do you think they are enough? If not, some of the other enchainements use travel signs, but we would have to add our own location signs.

**Comment by rsryman** [comment]
Let's start by considering these and see. I have downloaded the 3 examples
you sent and will have a careful look this afternoon.

I agree that we can add location signs if needed. We will say that these
are based on Sandy's notation, since we have to input them via MacBenesh
and perhaps simplify depending on the theory we have introduced?

**Comment by rsryman** [comment]
We have decided that this is not necessary in Book 4. We have enough simple examples of basic enchaînements. Bournonville content may be used in a future Readings book.
