### ISSUE TITLE
BB11 Review

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#19]
**DONE**

I was thinking about review questions for BB11.

1. We could have four different travel signs along the top with out of order labels "travel forward", "travel backward", etc., below. The reader would have to drag the label to match it with the correct travel sign.

2. We could have a stage plan with a shape drawn on it with travel arrows, an out of order sequence of starting location and direction, two travel signs, and an ending location and direction. The wording would be something like:
Drag the location, direction, and travel signs to match the sequence of travel on the stage plan.
  
3. There could also be a question with an animation making the pattern and two options of stage plans and the reader would have to select which one is correct? Unfortunately there would only be one question per page as I can't drag animations into the Review Widget. So I don't think we can do too many of these.

BTW, Arthur and I have been working on trying to create HTML5 widgets that can be dragged into iBooks Author. If we can get this working it may give us more flexibility for creating different types of Review Questions.

**Comment by rsryman** [comment]
I can work any time today so let me know if we should do a phone call or Hangout.

**Comment by rryman** [comment]
Since I couldn't edit the iba file on p. 34 (because it's a widget?), it 's simplest to give feedback here.
p. 33 I know you want to establish a “template” for wording the Review instructions; if so leave it as it was. This suggestion streamlines it a bit: "Reinforce your understanding and test your ability to read travel signs by doing the following review. This review contains three sections: the first contains ? questions, the second contains ? questions, and the section contains a maze puzzle."

p. 34: Questions 2-5 are excellent. I just had a problem with Question 1 of 5: the wording of sentences 2-3 is a bit confusing. Maybe we can discuss this via Hangout.
Suggest adding after sentence 1 (if room):
The tick is placed at the head of the arrow (either side) to indicate [travel forward/back].
The tick is placed at the tail of the arrow (either side) to indicate [travel sideways].
Then go on with your sentences 2-3:
The placement of the tick at either the head or tail of the shaft indicates [direction of travel].
The placement of the tick on either side of the head or tail of the shaft of the arrow indicates [direction faced] while travelling.
OR MAYBE:
The end at which the tick is placed indicates [direction faced] while travelling.
The side on which the tick is placed indicates [direction faced] while travelling.

Question 2 of 5 is clear (just change "the tick" to "a tick" in the bottom sentence?)
Questions 3-5 of 5 are great.
In Question 5 of 5, can you lower the buttons to separate them from the stage plan so they are not visually connected with it (just sequence in time not location re stage plan)?

After we talk about Question 1 of 1, maybe we can discuss ideas for the p. 35 question.

**Comment by rryman** [comment]
Please rewrite this question for me in the following format:
To fit on the area of the review widget, or broken into two pages.
There can only be (at most) 6 unique labels per question.

---

p. 34: Questions 2-5 are excellent. I just had a problem with Question 1 of 5: the wording of sentences 2-3 is a bit confusing. Maybe we can discuss this via Hangout.
Suggest adding after sentence 1 (if room):
The tick is placed at the head of the arrow (either side) to indicate [travel forward/back].
The tick is placed at the tail of the arrow (either side) to indicate [travel sideways].
Then go on with your sentences 2-3:
The placement of the tick at either the head or tail of the shaft indicates [direction of travel].
The placement of the tick on either side of the head or tail of the shaft of the arrow indicates [direction faced] while travelling.
OR MAYBE:
The end at which the tick is placed indicates [direction faced] while travelling.
The side on which the tick is placed indicates [direction faced] while travelling.

**Comment by rryman** [comment]
Rhonda said: After we talk about Question 1 of 1, maybe we can discuss ideas for the p. 35 question.

**Comment by rryman** [comment]
1. I have uploaded the most recent .iba file - Tuesday 4th April 9:00 am.
2. I have completed the ten questions for Review 3.1. Let me know if there are any errors, or you want any edits done to the questions.
3. I will update question 1 of 10 when you have reworded it to your satisfaction. It is no problem to add another page if you think that will work best.

**Comment by rryman** [comment]
I have uploaded 3 views of a first draft animation to test travel signs (without arms):
BB11Review1.m4v
BB11Review2.m4v
BB11Review3.m4v

Version 1 is the same zoom as in the body of the section, Version 2 is zoomed a bit more, and Version 3 is zoomed with the perspective "elevated." Let me know what works best.
I used a 3 beat intro and 6 bars of 3 beats each so we can notate this to 1 bar intro plus 6 bars of 3/4.

The direction faced+direction of travel is: 1) downstage left+side right; 2) downstage left+back; 3) downstage left+forward diagonal right; 4) downstage right+forward; 5) downstage left+back diagonal left; 6) front+side left. See attached screen shot of the Stage window:
BB11ReviewTopview

The order, line of travel, directions faced, etc., can be changed as you suggest to make the direction of travel more visible.

**Comment by rryman** [comment]
I think BB11Review3.m4v is probably the clearest for seeing the direction of travel.
Given that we haven't shown the reader how to use travel signs under a stave yet, I suggest I just have a series of 6 buttons on their own and not under a stave. Given this is the case, how about creating a version of this file without the metronome beat? We can then use this file with the metronome beat when we introduce the stave information in later chapters.

**Comment by rryman** [comment]
Yes, I agree that for this review we just ask readers to sequence the travel signs. I had anticipated reusing the animation in a later chapter with stave notation. Unless you have input about the clarity of the current sequence, I'll redo the BB11Review3 animation with arms that emphasize the dancer's alignment, and without sound.

**Comment by rryman** [comment]
I think the clarity of the current sequence is fine. It would be a bit more challenging if more of the line of travels were similar, but I hopefully it is challenging enough. See pic below to see how it looks in the book.
review3 2

**Comment by rryman** [comment]
What about sideways left downstage so that it is the same line of travel as the travel back to upstage right? That would make it two for each line of travel.

**Comment by rryman** [comment]
Rhonda said: "See uploaded animation: BB11ReviewJenna.m4v"

**Comment by rryman** [comment]
I'll add it to BB11 Review Q3.2.

**Comment by rryman** [comment]
Book 4 .iba file uploaded to DropBox - Thursday April 6, 4:45 pm.
Review BB11 is now finished except for the Interactive Maze Puzzle which requires Arthur's programming skills.
