### ISSUE TITLE
BB10 Location Puzzle

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#20]
Here is the sample svg file so you can see if this works before I continue with the rest of the locations.
[BB10Puzzel.svg.zip](https://github.com/rryman/BeneshForBalletBook4/files/865891/BB10Puzzel.svg.zip)

**Comment by rsryman** [comment]
I unzipped the archive and opened a "svg" file that was a stage plan with
uppercase letters at various points. Is there more?

**Comment by rryman** [comment]
Rhonda, you are not assigned to this thread. When Arthur and I have finished the puzzle, you will have an opportunity to view it in the Book on your iPad and then you can give us your feedback. I am just sending Arthur pieces so he can see if he can get the code working before I create the whole puzzle. To see who is assigned to an issue, look at the right-hand side of the GitHub Issue window under "Assignees".

**Comment by rsryman** [comment]
Sorry, your email said: "Here is the sample svg file so you can see if this
works before I continue with the rest of the locations."

**Comment by rryman** [comment]
I thought you might not be notified because you are not assigned to this issue, but that doesn't appear to be the case. I'll try to remember to address the comments with "Arthur" so it isn't confusing for you. I always go to GitHub to answer your posts, rather than answer them directly through email. That way I can keep track of things better.

**Comment by rsryman** [comment]
Yes, I think it's better to answer right in Github. Will so so from now on.
