### ISSUE TITLE
Interactive Stage Plan - On the Location

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#21]
**DONE**

Rhonda, please download the latest version of Book 4.
Please look carefully at Page 40  "Appendix - On the Location - Interactive Stage Plan" to make sure:

1. the location signs are correct - are they a good size and thickness, is the horizontal line now long enough, do any signs need to be tweeked?
2. the naming scheme meets your approval - wording, font size and type okay?
3. are the buttons a good colour?
4. are the buttons big enough?
5. any other changes required?

It is important to make sure this page is correct (and to your liking) as I will be using it as the template for the next three pages. The ripple affect of any change will be massively time consuming, so please take all the time you need to make sure you review this carefully so I can fix anything you don't like. Thanks!

**Comment by rsryman** [comment]
I downloaded the book and will look at p. 40 very carefully tomorrow.

**Comment by rryman** [comment]
Do you want me to make the horizontal ticks shorter?

**Comment by rryman** [comment]
I double checked these:
Middle right and left wing quarters, and middle right and left centre quarters.
The horizontal ticks are directly in the middle from the top to bottom so if they are beside other location signs like middle centre, the horizontal ticks will line up.

However, the longer curve at the bottom for wing quarters and top for centre quarters, makes the actual length of the line above and below the middle tick longer in total length so the tick doesn't look centred.

Do you want me to change this? Do you want the horizontal tick placed differently for these signs?

**Comment by rryman** [comment]
Changed the incorrect label. Good catch!

**Comment by rryman** [comment]
Note that the horizontal ticks are the same length as the ones used on page 8 of the book.

**Comment by rryman** [comment]
See the location signs in the interactive stage plan with red dots on page 40 of the newest book. These have the shorter horizontal tick as I had originally created them trying to match them the size in the encyclopedia. You found these too short. Remember that when these signs are shrunk further for use under the stave, i.e., page 13 and 14 the tick looks shorter. I really don't want to have to create multiple location signs and try to keep track of which ones are used where.

**Comment by rsryman** [comment]
Can we have a Google Hangout to discuss this thread? I can be at the computer 8-9 am Monday before my class or anytime after lunch.

**Comment by rsryman** [comment]
I defer to your judgement on this, Robyn. It's hard for me to to decide between two options in isolation, without seeing the two options side by side. You have to create all of the signs and have thought most about how to do it, so I'll go with your preference.

**Comment by rryman** [comment]
Latest .iba file - Monday March 27th, 2:36 PM
Please look at page 39: 

1. Are the smaller location signs okay for this interactive stage plan?
2. Did I introduce any new errors?
3. Does anything jump out at you that needs tweeking?
4. Any other edits needed?

I will move onto creating the interactive stage plans for pages 40, 41, & 42 when we are absolutely sure nothing needs to be updated on page 39.
