### ISSUE TITLE
BB10 Proofreading

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook4#22]

**Comment by rryman** [comment]
.iba file uploaded Monday March 27th, 2:36 PM

I have made the location signs smaller on pages 8, 9, 10, 11, 12 (only under the stave), and 15.
Please let me know if the sizes of these signs are okay for you when you view them on your iPad.

**Comment by rryman** [comment]
Are you okay with the footnote I added on page 7?
*Note: the location signs slope left to represent the left side of the stage, and slope right to represent the right side of the stage.

**Comment by rsryman** [comment]
I have gone through BB10 pages 5-18 and made comments in blue on RhondaBook4.iba, uploaded to Dropbox. (I think you can now delete Book4RR.iba?)

**Comment by rryman** [comment]
Suggested rewording of Footnote on Page 7

Your suggestions:
The performing area may be divided into fewer or more sections, with the notator modifying and glossarising location signs as needed (a practice not covered in this book).

My suggestion:
**When the performing area is divided into fewer or more sections, the notator uses _site specific location_ signs (not covered in this book).**

**Comment by rryman** [comment]
Sorry, I don't understand this comment:
Final sentence: we need to clarify that the "full set of 63 discernible location signs and their meanings" is actually 63 with the tick centred, and so on for the next 3 pages. Discuss wording by phone?

**Comment by rryman** [comment]
Is it okay if I took out the "Note:" from the footnotes (p. 9, 10, etc.).
It isn't really needed is it?

**Comment by rryman** [comment]
Page 13 Footnote:
Your wording:
The eight basic direction signs and the room numbering systems used in the English, Italian, and Russian schools introduced in Book 1 are reproduced in the Appendix p. ??.

Can we add some brackets to this sentence?
The eight basic direction signs (and the room numbering systems used in the English, Italian, and Russian schools) introduced in Book 1 are reproduced in the Appendix p. ??.

**Comment by rryman** [comment]
Page 15 and 16: What about the title ... Other Descriptions for Locations?

**Comment by rryman** [comment]
Page 15 - is it okay if I take out the **the**?
In practice, a variety of theatre terms may be used to describe the dancer’s location. For example, the Royal Academy of Dance (RAD) _Set Exercises and Variations_ publications use **the** descriptions such as those below:

**Comment by rryman** [comment]
Page 15 footnote okay to use "descriptions" instead of terms?:
*The RAD Set Exercises and Variations publications refer to the BMN left or right half as the left or right quarter, respectively. In practice there is no confusion, since the location signs clarify the dancer’s location and supersede the wording. See Appendix p. ?? for more details about RAD **descriptions** for locations.

**Comment by rryman** [comment]
New .iba file uploaded with your suggested changes. Use it to go through the comments above.

**Comment by rsryman** [comment]
Sorry I'm a bit behind today. 

I was going to do BB11 Proofreading next. Should I do that before downloading the most recent iba file and replying to your updates re BB10, or would the pagination not have changed re BB11?

**Comment by rsryman** [comment]
Proofreading only the items listed above in BB10:
√pages 8, 9, 10, 11, 12 (only under the stave), and 15: location signs smaller
√page 7: one footnote incorporated into para 1, sentence 3; other footnote updated
√page 8: full set of discernible "on the location"  _location_ signs.
√page 9: full set of discernible "right of the location"  _location_ signs.
√page 10: full set of discernible "left of the location"  _location_ signs.
√page 11: full set of discernible "between locations" _location_ signs.
√pages 9-11: delete "Note:" from the footnote.
√page 15 and 16:  title updated: Other Descriptions for Locations; sentence 2 reworded

page 13: wording of footnote still to be discussed. Rhonda's reply (Mar31/17) - Suggestion: Appendix p. ?? presents the eight basic direction signs and the corresponding room numbering systems used in the English, Italian, and Russian schools, as introduced in Book 1.

**Comment by rryman** [comment]
Footnote page 13:
I have changed it to this:
*Appendix p. ?? presents the BMN eight basic direction signs and the corresponding room numbering systems used in the English, Italian, and Russian schools, as introduced in Book 1.

**Comment by rryman** [comment]
Footnote page 15:
Because of changes to page 46 based on Liz's input, I have updated the footnote to:

See Appendix p. ?? for more details about descriptions for locations used in RAD word notes.

**Comment by rsryman** [comment]
**DONE**
I downloaded and synched the iba file you uploaded April 9, 1:53 pm and checked the revised footnote on p. 15 (referring to the Appendix p.46).
