### ISSUE TITLE
Right of Location

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#24]
**DONE**
Before I do all 63 entries for this page, please look at two images below.

1. Note that I have taken out the comma. I took it out on the previous page and used the same format here.
2. My original thought was to have the entries on two lines (see the first image). However, due to the proximity of the right-hand pop-up window to the right-hand margin of the book, I am unable to make this entry two lines as it is too wide to fit (see second image). So to be consistent, do you agree that all the pop-up entries should be three lines and not just the ones right of right wing?
(We will have the same issue with the left-hand margin for the left of location page.)
3. Are the grey buttons far enough to the right of the locations?

![rightoflocation2](https://cloud.githubusercontent.com/assets/15850667/24617689/aac1d050-1862-11e7-9484-3286e426c1d2.jpeg)
![rightoflocation](https://cloud.githubusercontent.com/assets/15850667/24617691/ac872034-1862-11e7-9434-f7c4955dfbe1.jpeg)

**Comment by rsryman** [comment]
The three-line entry looks fine and compact. 

But rather than changing all, would it be sufficient to just split the longer ones? Some of the "between location" labels are bound to be long.

**Comment by rryman** [comment]
As discussed via phone ... I am going to make the pop-up text 3 lines for the "right of" and "left of" location pages.

**Comment by rryman** [comment]
I have found a way to make the pop-ups at the margins expand, so we can do the two line option in all cases. I asked Arthur's advice and he thinks two lines is better - y co-ordinate info on one line and x co-ordinate info on the next line. I think I can make this work in all cases - even between locations.

**Question: do we need "just" for the "right of" and "left of" locations?
Could we say "left of right wing" instead of "just left of right wing"?
The Benesh Encyclopedia says "a little to the right of the left wing", and "half way between the left half and the left centre quarter". We just say "between left half and left centre quarter", so maybe we could get away with "right of left wing".
I would like us to decide this before I do any more work on the interactive stage plans.**

**Comment by rryman** [comment]
Do you think we should add another footnote saying something like ...
Though some of these location signs look similar to travel signs when seen in isolation, when used in context there is no confusion.
![rightoflocation2](https://cloud.githubusercontent.com/assets/15850667/24706127/a74669f6-19dc-11e7-8261-58832e0a0a04.jpeg)

**Comment by rsryman** [comment]
What about: Note that the tick on a location sign is always horizontal. Though some of these location signs look similar to travel signs when seen in isolation, there is no confusion when they are used in context.

**Comment by rryman** [comment]
Robyn still to complete all location signs for this Right of Location Interactive Stage Plan.

**Comment by rryman** [comment]
I have completed the "Right of the Location" page in the Appendix.
See page 42 of the most recent uploaded .iba file (Friday 7th April 1:16 pm)

Please proofread carefully because:
1. Location signs: I will be copying all of the location signs and flipping them in Adobe Illustrator one at a time for "Left of the Location" and then placing each one into each pop-up box in the book.
2. Text: I will be copying the entire page and just changing "right of" to "left of" in each pop-up box.

Please do as many passes as you need in order to check for:
1. Errors
2. Text fonts and formatting
3. Signs that need to be tweeked. If they need to be tweeked please tell me exactly how you want me to tweek them. I tried to only change the curve on the ones that were totally illegible otherwise. I tried to keep the heights of all horizontal lines the same for all location signs (despite the optical illusion where some horizontal ticks don't look to be in the centre of some of the curves).
**All signs and sizes are based on the agreed upon signs and sizes on Page 9.**
4. Distance of grey dots from the location signs.
5. Footnote text.
6. Any other problems.

**Comment by rsryman** [comment]
Rhonda proofreading p. 42: 
1.&2. I didn't find any errors or problems with text fonts and formatting.
3. All these signs should be legible in context, as explained in the footnote. 
However, the least clear signs are the ones at the frontmost and backmost edges of the stage,
especially the 4 signs at the frontmost edge on the halves and centre quarters and the 4 signs at the backmost edge on the halves and wing quarters.
**Perhaps we can make these ticks longer as you did on p. 41. 
Question: for all 18 signs at front/back edges or only the 8 problems mentioned above?**
4. Grey dots on stage plan at a clear distance from vertical lines
5. Footnote text fine.
6. Nothing else.

**Comment by rryman** [comment]
I was concerned about making the tick longer because I want it to be recognizably shorter than the tick for "on the location". Due to the slope of the curves it is hard to tell that the tick is only on one side. Perhaps we can do this in a Google Hangout where I share my Adobe Illustrator screen and then we view the signs in reduced mode?

**Comment by rryman** [comment]
Rhonda, I am a little confused:
especially the 4 signs at the frontmost edge on the **halves** and centre quarters and the 4 signs at the backmost edge on the **halves** and wing quarters.

Do you mean wing quarters and centre quarters?
The only signs I find really problematic are:
Frontmost edge right of left centre quarter
Frontmost edge , right of right centre quarter
Backmost edge,  right of left wing quarter
Backmost edge,  right of right wing quarter

For these sign I changed the slope of the curve, made the horizontal tick slightly thicker and a tad longer. As I said above, I was worried about making the horizonal tick too long as it started to look too much like "on the location".

Please clarify what other 4 signs bother you.

**Comment by rsryman** [comment]
Yes, problems:
Frontmost edge , right of left centre quarter (similar to curved travel fwd, tick could be longer?)
Frontmost edge , right of right centre quarter (not too bad but don't know how to improve it)
Backmost edge,  right of left wing quarter (most unclear but don't know how to fix it)
Backmost edge,  right of right wing quarter (similar to curved travel back, tick could be longer?)

I also found some on the halves unclear (very similar to travel signs), but readable in context:
Frontmost edge , right of left half (looks like travel forward, horizontal tick could be longer?)
Backmost edge , right of right half (looks like travel back, tick could be longer?)

These aren't bad but perhaps tick could be longer or thicker:
Frontmost edge , right of right half  
Backmost edge , right of left half 

You've done a great job on the near front/back signs so they can't be confused with side travel. The few below might be a problem although they should be clear in context and because the tick is horizontal. Might they be easier to read if the tick were longer? 
Near front , right of right half (looks like travel right)
Near front, right of left wing quarter (looks like curved travel right)
Near back , right of left half (looks like travel left)
Near back, right of left wing quarter is clear.

I'm home and available if you'd like to talk these through.

**Comment by rryman** [comment]
I tried calling. Do you want to do a Google Hangout now?

**Comment by rryman** [comment]
We had a Google Hangout on this topic. I showed Rhonda the modifications I had done to each sign and explained why it was perhaps not advisable to lengthen the horizontal signs. We have decided to leave the signs as is and will only change them if we receive negative feedback from our readers.
