### ISSUE TITLE
BB11 Review Proofreading

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#25]
**DONE**

Sis, when it is convenient, download the latest .iba file and proofread BB11 Review - pages 33, 34, and 35. Please post your comments to this issue thread.

**Comment by rsryman** [comment]
Fun review!

p. 33: typo in line 2: "the second contains one questions" -> "the second contains one question"

Maybe run these 2 by Arthur:
p. 34 suggested rewording: Drag the label to the buttons that complete the sentences.
p. 35 suggested rewording: Drag the travel signs to the buttons that match the order of travel in the animation.

p. 36 The maze puzzle looks like fun, but I couldn't get it to work. I did find the instructions and read them, but perhaps make the "Maze Instructions" rectangle bigger/more prominent.

**Comment by rryman** [comment]
Here is Arthur's suggestions:
Page 34: Q. 1 of 10 and 2 of 10:
Drag each label to its corresponding button in order to complete the sentences.
Page 35: 
Drag each travel sign to its corresponding button so that it matches the order of travel in the animation.

**Comment by rryman** [comment]
Page 19 and Page 36: I am limited as to how big I can make the puzzle instruction label on these two pages because it alters the drop-down menu. I have made them both slightly bigger for now (based on your input), but the size may have to change once Arthur has programmed the puzzles and the instructions are finalized.
