### ISSUE TITLE
Book Comment

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#28]
Meta data that has to go into the Inspector Window of the .iba file needs to be updated for Book 4:

_Benesh for Ballet: Book 4_ builds on Books 1, 2, and 3 to introduce sequences that travel. Book 4 helps students and young teachers continue to learn how to read Benesh Movement Notation (BMN) with the aid of stage plans and animations. This book features an extensive Glossary of definitions and cross-references for vocabulary terms from the three major ballet "schools": English, Italian, and Russian used in Books 1-4.

**Comment by rsryman** [comment]
Here is a first pass:

_Benesh for Ballet: Book 4_ builds from Books 1, 2, and 3 to introduce sequences that travel around the performing area. Book 4 helps students and young teachers read basic jumps, steps, and slides with the aid of Benesh Movement Notation (BMN) stage plans and DanceForms animations. This book features three challenging interactive puzzles that test the reader's understanding, and also an extensive Glossary of definitions and cross-references for vocabulary terms from the three major ballet "schools" (English, Italian, and Russian) used in Books 1-4.

**Comment by rryman** [comment]
Here is a second pass:

_Benesh for Ballet: Book 4_ introduces Benesh Movement Notation (BMN) _stage plans_, _location_, and _travel_ signs which are useful tools for dancers, choreographers, actors, stage managers, etc. The final two chapters build on theory covered in Books 1, 2, and 3 to present sequences with jumps, steps, and slides that travel around the performing area. _Book 4_ contains DanceForms animations, interactive puzzles, and an extensive Glossary of definitions and cross-references for vocabulary terms from the three major ballet "schools" (English, Italian, and Russian) used in Books 1-4, making it a valuable resource for ballet students and teachers.

**Comment by rsryman** [comment]
Much improved. Just a few suggested tweaks:

*Benesh for Ballet: Book 4* introduces Benesh Movement Notation (BMN) *stage
plans *and also *location* and *travel* signs – useful tools for dancers,
choreographers, actors, stage managers, and theatrical stagers. The final
two chapters build on theory covered in Books 1, 2, and 3 to present
sequences with jumps, steps, and slides that travel around the performing
area. *Book 4* contains DanceForms animations, interactive puzzles, and an
extensive Glossary of definitions and cross-references for vocabulary terms
from the three major ballet "schools" (English, Italian, and Russian) used
in Books 1-4, making it a valuable resource for ballet students and teachers
alike.

**Comment by rryman** [comment]
It all fits in the metadata window! There is no way to italicize things in the Inspector Window, but that's okay.

**Comment by rryman** [comment]
Let's not close this issue, as I should probably use something similar when I update the promotional flyer.

**Comment by rsryman** [comment]
Yay! Nice that something works, given the "challenges" (aka headaches) you
have recently been meeting in iBooks Author.....

**Comment by rryman** [comment]
Robyn to create a word doc of all the Description data from the iBooks store for Books 1-3 and the meta data from Book 4.
