### ISSUE TITLE
Left of Location

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#29]
I have completed the interactive stage plan for "left of location" page 43.
Please let me know if I have made any errors.
I am only interested in changing what is actually wrong.
The signs are a reflection of "right of location" so shapes and sizes will be the same. The signs that were unclear for "right of location" will still be unclear in "left of location". So unless something is totally illegible, I don't want to change them unless all of our proofreaders complain about them.

**Comment by rsryman** [comment]
Signs and labels checked.
