### ISSUE TITLE
Between Locations

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#30]
I have completed the interactive stage plan for "between locations" page 44.
Please let me know if I have made any errors.
I separated some of the signs that were more problematic, i.e., frontmost and backmost.
I changed the slope of the curve when it is used with the "centre" location so the gap isn't as wide.
If there are any signs that REALLY bother you and you can tell me exactly what to do to make them more legible then I will give it a try.
I made all these signs slightly bigger than the other signs in the previous interactive location plans because the size of the horizontal line shouldn't be a problem like it was for you with the other signs when they were bigger.

**Comment by rsryman** [comment]
Signd, labels, and text all checked. These composite signs are very clear, bravo!
