### ISSUE TITLE
Chapter5 BeneshBasics13

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook4#35]
Re  INTRO TO JUMP, STEP, SLIDE LINES, see files uploaded to For Robyn > CH5S1 folder:

Added 5 animations to p. 61:
BB13JumpJenna.m4v, BB13StepFwdJenna.m4v, BB13StepBkJenna.m4v, BB13SlideFwdJenna.m4v, BB13SlideBkJenna.m4v
I exported the animations using window dimensions 336W x 352H. 
I suggest we show the definition of jump, step, slide as footnotes on pages 60 & 61, to save space for the animations.

Added 3 animations to each of pages 62-63:
2-1FwdJenna.m4v, ClassWalkFwdJenna.m4v, ChasséFwdJenna.m4v
2-1BkJenna.m4v, ClassWalkBkJenna.m4v, ChasséBkJenna.m4v

On page 65, I suggest moving sentence 2 from para 1 to below the animations (to de discussed?) NOTE: I increased the altitude on these to position the dancer above the playback bar. Helpful? Added 4 animations to page 65:
BB13ClassicalWalksFwdRJenna.m4v, BB13ClassicalWalksFwdLJenna.m4v, BB13ClassicalWalksBkRJenna.m4v, BB13ClassicalWalksBkLJenna.m4v

RE page 66, can we decide on a starting positions: 5th vs classical pose vs pointe tendu
See sample animations on p. 66

Animations uploaded & added to p. 67 (1), 68 (3), 69 (3), 70-72 (3), 73-74 (4), 75 (6), 76 (2)

**Comment by rsryman** [comment]
The sound wasn't playing well in the 2 animations on p. 76 so I just updated them and revised the .iba file. Be sure to download the latest one: July 19. An interesting tip: I was able to delete the old animation but retain the widget then drag in the new file. Saves a bit of time.

**Comment by rsryman** [comment]
I GUESS IBOOKS AUTHOR CANNOT TAKE .mp4 FILES. SEE BELOW:
Re p. 72 Eliane sent a clipped version of "BB13ChasséPdB_Corn2Jenna.m4v" which she called  "Trial_em.mp4." I added it at the end of Book4, page 112. Eliane clipped my file to 320w x 212h but the widget wouldn't accept that height. I had to rescale it to 365x342 and that dimension allowed me to add her mp4 file but caused iBook Author to crash. When I reopened Book4, the animation played jerkily, then the app crashed and I couldn't open the file. Thankfully I was able to retrieve the version I uploaded from Dropbox yesterday night.

**Comment by rryman** [comment]
I was able to put an .mp4 file into the iBook. iBooks Author is supposed to support any file format that can be played using QuickTime. Please send me Eliane's file so I can see if I can add it. Thanks.

**Comment by rsryman** [comment]
Hi sis. It's in your Dropbox > For Robyn folder.

**Comment by rsryman** [comment]
To follow up to our conversation about minimizing whitespace, I realize that the size constraints have been changing. My previous version showed the full stage width in the window (at least at the front) and sometimes the dancer's feet above the playback bar. If not an issue now, see sample in Dropbox re p. 72, dimensions 600Wx400H: BB13ChasséPdB_Corn2JennaZ.m4v

If this is acceptable, I'll make zoomed versions of other animations as needed.

**Comment by rryman** [comment]
SO much clearer to see. I especially like the addition of the red shoe.
I viewed the animation on my iPad. Given that we have lost the battle with the playback bar covering the animation, can we at least give the reader a few seconds of silence in order to tap to get rid of the playback bar before the animation starts, or is that too much trouble?

**Comment by rsryman** [comment]
We need to talk about animations with Sound. 
Problem 1: To Export a DanceForms file to .mov format, I need create Sound files that correspond to the number of beats or bars in the animation. I can easily Trim the end of a Sound file in QuickTime but I can't figure out how to (digitally) add silence at the beginning. The way I have been getting around this is to rerecord the Sound file (make an analog recording): I start playing the file on one machine, wait a second, then hit record on another. That produces a second of silence at the start but creates the "hollow" sound I noticed in Book 3. As always, there's a trade-off. 
Problem 2: In this book, I haven't been consistent in using unaccented metronome beats (a continuous number of beats) versus accented metronome beats (to differentiate 2/4, 3/4 , etc.). There is a reason for this which we can discuss.
Ideas welcome.

**Comment by rryman** [comment]
To be honest, I wish we could not use the metronome beat. What about counting?
I wish there was a way that we could use snippets of music.

**Comment by rryman** [comment]
Or at least vary the metronome beat so it isn't the same one all the time. I wonder if I can take the clip into iMovie and digitally add white space at the beginning so we don't have that "hollow" sound?

**Comment by rsryman** [comment]
I could go through the Richard Maddock clips we used in Book 2 and see if
any might work, but I think they all have intro bars which would rule them
out. I didn't use any intros since that would have made the BMN too long.

**Comment by rryman** [comment]
Do you have the Richard Maddock clips? I could see if I could edit out the intros.

**Comment by rryman** [comment]
Would you be able to ask your music friend if he knows of any free electronic classical music sites that he trusts?

**Comment by rsryman** [comment]
I'll boot my laptop and look for something appropriate. In the meantime,
you could download a clip from his website and do a test.

**Comment by rsryman** [comment]
We solved the problem by Trimming the end of a file in QuickTime and adding a second of silence at the beginning in iMovie.
