### ISSUE TITLE
ToAddressBeforePublishing

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook4#36]
Add a 1-sec. delay at the start of animation NB BB13 Locomotor Actions Step, Slide 

Add note in How to Navigate this Book: 
In order to show larger animated figures, we had to sacrifice having the Playback bar clear the figures. We have therefore provided a 1-sec delay at the start of most animation to give you time to tap quickly to make the playback bar disappear.

**Comment by rryman** [comment]
Do a global search:
Encyclopaedia
Prepositions for capitalization in titles:
from, with, and, the, toward, through, ?
Path (not line)
