### ISSUE TITLE
Music&SoundFiles

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook4#37]
Robyn, see uploaded file with music IN DROPBOX CH5S1 FOLDER: BB13ChasséCoupéJenna.m4v

To be included in acknowledgements:
Downloaded from Richard Maddock's Website http://www.richardmaddock.com/music.html

Below for Rhonda's info only re adding sound to animations:
**Music for Movement and Imaginations:**
**Track 11.** Pointing & Tendus | 2/4 (4 bar intro + 8 bars 2/4) to be clipped (1/2 beat pick-up + 1 bar of 2/4) and used for ACTIONS TRAVELLING FORWARD (Galop: temps, levé chassé, coupé sauté)
**Track 21**. Swaying & Rocking (4 bars of slow 3/4 maybe for temps levé chassé pas de bourrée)
**Track 36.** 1 bar 2/4 To be used for: On the Count versus Through the Music
**Track 34.** (4 bar intro + 8 bars) clip to 2 bars of slow 3/4 to use for TRAVEL AND LOCATION SIGNS… courus

**Comment by rsryman** [comment]
See uploaded file, setting p. 30 animation to music re p. 92:
BB11TravelFwdRectanglep92.m4v

JUST A TEST TO SEE IF THE GALOP MUSIC WORKS. 
To match the music file, I had to slow down the animation a bit. This works better, I think.
The current movie has a **1-bar** intro plus 16 bars of 2/4 Galop, counting 1 bar per chasse-coupé (Track 11). It should have a 1-second silence then a **1-count** intro, but I cannot remember how to add a 1-second silence in iMovie so this animation starts too abruptly. When we both have time, I will need a refresher on iMovie before I attempt the rest of the animations.

**Comment by rryman** [comment]
I am working on the book at present. I may have to leave at 2:45 to take Emma to the eye doctor, but call me if you want to add the silence in iMovie.

**Comment by rsryman** [comment]
Thanks for your help with iMovie. See 3 new animation files uploaded to Dropbox > For Robyn folder:
BB11TravelFwdRectanglep92.m4v
BB13ChasséCoupéArrièreJenna.m4v
BB13ChasséPdBJennaEnFace+.m4v

On p. 72, we say "chassé, coupé" but on p. 92/3? "chassé, coupé sauté." 
Please add a blue note reminding me to do a Glossary Entry. 
p. 72: suggest: Chassé, coupé sauté en avant performed twice, travelling toward the audience, to two bars of 2/4 music.
p. 73: suggest: Chassé, coupé sauté en arrière performed twice, travelling away from the audience, to two bars of 2/4 music.
p. 92/3? title Chassé, coupé sauté en avant

**Comment by rsryman** [comment]
To summarize our email discussions, re **Music for Movement and Imaginations** - we have decided to use: 
**Track 34** for courus pp. 81, 82, 83, and 96
**Track 21** (the present courus music) for the chassé pas de bourrée pp. 76, 95, 97, and 99.
To make this a bit more interesting, I will use the 4 intro bars for CH 5 and the body for CH 6.

**Comment by rsryman** [comment]
Animation files with correct music uploaded to For Robyn (refer to pages numbers in latest .iba):

**COURUS** 
**Music for Movement and Imaginations** Track 34: the intro bars:
p. 81 BB13CourusPlaceTournantR.m4v & BB13CourusPlaceTournantL.m4v
p. 82 BB13CourusForward&Right.m4v & BB13CourusBack&Left.m4v

**Music for Movement and Imaginations** Track 34 the body of the music: 
p. 83 BB13CourusStageJennaP83.m4v

p. 96 BB13TravelSideLeftp96.m4v 
Track 34 didn't work for p. 96 so I used **Ballet Studio Inspirations: Volume 3** Track 30 - slow enough to make the desired pattern. I spent a lot of time refining the arms & body, so we could also update p. 36 silent version if you like. Let me know.

**CHASSÉ PDB** (Track 21) 
(pp. 76 & 84 are already in the iBook)
p. 85 BB13ChasséPdB_Corners2Jenna.m4v
p. 86 & 97* TravelDiagonalChasséPdBP97.m4v
p. 87 & 99* TravelDiagonalChasséPdBP99.m4v
***Pages 86 & 87 use the same material as on pages 97-99. Why twice?**
Re pp 86/97, right red foot added. Re BMN, please use a head turn only on Bars 1, 3, 5, 7 ct 1 (chassé) and head erect on Bars 2, 4, 6, 8 ct 1 (demi-plié) to simplify and match these animations.

**Comment by rsryman** [comment]
See correct music re p. 83 (file now uses Track 34) uploaded For Robyn > BB13CourusStageJennaP83.m4v 

I'm still searching for where I used a very slow 3/4: **Ballet Studio Inspirations: Volume 2** Track 1

**Comment by rryman** [comment]
When all the animations are completed, please send me an updated list of
the music clips you used for the animations so I can correct them in Book 4.

**Comment by rsryman** [comment]
Runs in circle & figure 8 (pp87-88): MMI Track 36 (2/4)

**Comment by rsryman** [comment]
TravelBackwardWalk (in square) MMI Track 16 4/4 Andante (4 bars)

**Comment by rsryman** [comment]
See attached summary: Book4SoundFilesList.docx

**Comment by rsryman** [comment]
Animations should have a 1-second silence at the beginning and end. 
To create the accompanying Sound file:
1.  Trim the end of a clip in QuickTime.
2. Add a second of silence at the beginning in iMovie, then Share audio only as .aiff.
