### ISSUE TITLE
AnimationUpdatesFrom July24/17

### ISSUE THREAD

**Issue by rsryman** [rryman/BeneshForBalletBook4#38]
Rhonda to update figures & animations based on our phone conversation (page numbers based on my file BeneshForBalletBook4_RRK.iba July22/17):

**Benesh Basics 11**
pp. 24-28 separate figures to start; add red/right & black/left glove; zoom if possible?
pp. 30,32,34,36,39 animations to be left as is, but consider updating the bottom note: "For a zoomed view of this sequence with music and corresponding stave notation, see page ??."
pp. 38,40 add red/right & black/left glove to update 8 figures + 8 animations 
p. 41 Create new animation (and update the caption?)
p. 44 Still to do: update arms in 2nd?

**Benesh Basics 13**
p. 66 Start pointe tendu derrière for runs forward, devant for runs back; arm en bas throughout
p. 6, add right red foot
pp. 68 refine the step R/L to not pass through demi-pointe
pp. 70-72 add right red foot & music; zoom if possible?
pp. 73-74 consider adding music rather than metronome
p. 75 first 2 should be on demi-pointe; cross feet less and lift a bit for clarity
p. 76 cross feet less

**Comment by rsryman** [comment]
I started by updating the animation on ACTIONS TRAVELLING FORWARD p. 67 since I had it open, but from now on I'll go in order from p. 24. 

Let me know if it is helpful for me to put the new animations in a new folder: 
For Robyn > AnimationUpdatesJuly24,2017 >  BB13ChasséCoupéJenna.m4v

**Comment by rsryman** [comment]
I just uploaded 16 files for pages 24-27. 
I tried to make the coloured hands visible outside the initial Playback arrow/circle. 
Let me know if this isn't enough.

**Comment by rsryman** [comment]
Working on Diagonal static images and animations re pp. 38, it occurred to me that we need gloved figures on animations for pages 29,31,33,35&37, yes? Will wait to confirm.

I have uploaded figures and animations for page 38.

**Comment by rryman** [comment]
Yes, I think gloved figures would be good for those pages.

**Comment by rryman** [comment]
Re 16 files for pages 24-27: One person pokes out a little more than the other. If you want to change it, I'd change the person who sticks out less to match the one that sticks out more. But I'll leave it up to you as to whether you think it is worth changing or not. Just let me know, as I won't add any more of the animations until I hear whether you plan to change them or not.

**Comment by rryman** [comment]
It looks like you have put the updated animations in the new folder. This is not a problem for me, but you should delete the old files from the other folders. I am deleting files as I copy the animations into the book, so I can keep track of which ones I have done so far.

**Comment by rsryman** [comment]
Can you call me on Hangout so I can see what you mean? Anytime today is
fine.

**Comment by rsryman** [comment]
Please look at the revised animation for page 23 in For Robyn > CH3S1 folder: 
CH3S1travelupst-downstP23.m4v

This is to replace the older file of the same name (the one you sent to Ros) in the For Robyn folder IF/WHEN you approve it. Note that the name of the file on p.23 (inspector window) is "CH3S1p22.m4v" - I can rename the revised file when you approve the changes-- before I proceed:
1. New right arm on red figure, to match dimensions of other 3 figures.
2. Zoom to fit window (bottom figures will start under grey Playback bar) - we may need to move the "Hint" from the following page to this page

**Comment by rsryman** [comment]
To summarize our phone conversation and clarify what I am doing:

1. I will start by updating the BMN clips and give you a ps of the revised notation, one page at a time.
2. Then I will update all animations from the beginning of BB11 (coloured figures) to show a gloved hand (index finger and thumb). I checked the position of the index finger. It is the same in all figures so the inconsistent crooked look is beyond my control.
3. I will retain the .m4v file name shown in my RRK iBook media inspector window and upload each to the CH3S1 folder, overwriting the old file. You should use files dated July 25 or later.

When I start revising the animations I will want to preview the playback on my iPad. Let's hope Apple has addressed the problem by then.

**Comment by rsryman** [comment]
On July 27/17 I uploaded revised animation files for all animations in BB11 pages 23-28 and 37-40 into Dropbox > For Robyn > CH3S1

I did my best to colour the extended hand, index finder and thumb and adjust the pointing finger. Please call if you see anything amiss before you input all of these.

I still have to colour the extended hand, index finder and thumb and adjust the pointing finger on pp. 29, 31, 33, 35.

I have a note reminding me to update the animations on p. 41 and the Review on p. 44 (arms in 2nd?) -- but I can remember how, can you?

**Comment by rryman** [comment]
"On July 27/17 I uploaded revised animation files for all animations in BB11 pages 23-28 and 37-40 into Dropbox > For Robyn > CH3S1"

**I think it is best if I don't put in the animations until I know you are no longer doing any work on them.**

"I have a note reminding me to update the animations on p. 41 and the Review on p. 44 (arms in 2nd?) -- but I can remember how, can you?"

**You don't like the idea of just keeping the arms in 2nd through with the head erect do you? It is just that it is difficult to see the way the dancer is facing when bourreeing on pointe and I think an erect head and stable arms in 2nd would help the reader focus on the diagonal direction of travel. If you really think that would look bad, then let's go through the sequence again via a Google Hangout and we can go over the way we agreed to use the arms in second with port de bras.**

**With the animations for the travel patterns is there a way to make them bigger? If we aren't worrying about the playback bar blocking the animation any more, is it possible to lower the stage to the bottom of the window? Does that make the zoom bigger? Is there a way of cropping out the white space above the dancer when you export these particular animations from DanceForms?**

**Comment by rsryman** [comment]
See 2 new animations we talked about last night, uploaded to Dropbox > For
Robyn

If you approve the dimensions, perspective, etc. I will use the p. 41
animation as a template for the rest in the same chapter, them replace the
old files in the folder you will use to paste animations into the iBook. OK?

**Comment by rryman** [comment]
The replacement for the diagonal travel for p. 41 is much better. Bravo!
 
Is is possible to cheat a little on the animation for the review question and have Jenna's body face a little passed the left downstage corner so that it is really clear to see her facing the corner on the diagonal bourrees downstage and upstage (especially upstage). If it isn't possible, or you think it will look odd then don't worry about it. It is definitely clearer than it was now the arms are in demi-seconde, and the reader can select the easy directions signs first and can then work out the two diagonal ones.

**Comment by rsryman** [comment]
Heading out for our walk before it rains but I'll get to this as soon as we return. 

You and Arthur hosted a beautiful party yesterday, sis. Hope you can gear down now. 

Love,

Sis

**Comment by rsryman** [comment]
BB11 animation files uploaded into Dropbox > For Robyn > CH3S1

Re pp. 29,31,33,35, 37: in these 5 files, I added a coloured glove on the extended arm (red/right, left/black), extended the fwd arm to match the other directions, & straightened the index finger as best I could. See 5 updated .m4v files, named as in inspector window. 

Re pp.30,32,34,36,39, 41: Consider updating note at bottom of these pages:
"To see Jenna perform a larger version of this sequence to music, with corresponding stave notation, locations and travel information, see page ??." This fits on one line at 14 pts.

I updated animations for pp. 30,32,34,36,39 using the perspective/zoom & dimensions we agreed on for p.41 (300x600)
**NOTE THAT THE FILE NAMES DIFFER FROM THE INSPECTOR WINDOW:**
p. 30: BB11TravelFwdRectanglep30.m4v 
p. 32: BB11TravelBackwardWalkp32.m4v
p. 34: BB11TravelSideRightChPdBp34.m4v
p. 36: BB11TravelSideLeftBourréep36.m4v 
p. 41: BB11TravelDiagonalp41.m4v
(Re p.41, I shifted the dancer upstage to make her larger. Robyn to update the BMN stage locations.)

P. 44 Review 3.2 animation revised arms retained in demi-2nd: BB11ReviewJenna.m4v

**Comment by rryman** [comment]
I thought we had agreed to move the dancer to match the notation even though it meant being inaccurate from the aerial view of danceforms? Have you looked at these animations in relation to what is notated in Book 4? Do they look accurate to you?

NOTE THAT THE FILE NAMES DIFFER FROM THE INSPECTOR WINDOW:
p. 30: BB11TravelFwdRectanglep30.m4v
p. 32: BB11TravelBackwardWalkp32.m4v
p. 34: BB11TravelSideRightChPdBp34.m4v
p. 36: BB11TravelSideLeftBourréep36.m4v
p. 41: BB11TravelDiagonalp41.m4v
(Re p.41, I shifted the dancer upstage to make her larger. Robyn to update the BMN stage locations.)

**Comment by rsryman** [comment]
I have looked at these so long that I can't see them anymore so I defer to
your judgement.

Can we adjust these together later today?

**Comment by rryman** [comment]
Please download the recent version of Book 4 from DropBox. That way we can both be seeing the animation files in the context of Book 4 as we go through them together. We can decide if the animations, or the notation, need to change.
