### ISSUE TITLE
Stage Plan Puzzle Widget Should Have a Status Line

### ISSUE THREAD

**Issue by agryman** [rryman/BeneshForBalletBook4#43]
At present the widget pops up a "Congratulations" alert dialog when the user solves the puzzle. Replace that with a status line that shows the progress. For example, 
   You've solved 16 of 37 clues.
or 
   Congratulations, you've solved the puzzle!

**Comment by rsryman** [comment]
I vote for "Congratulations, you've solved the puzzle!"

I think that 37 status line updates might get annoying. The green versus
red colour is a good cue of error versus success.

**Comment by agryman** [comment]
@rsryman OK. I've updated the widget using your text.

**Comment by agryman** [comment]
I updated the StagePlanPuzzle iBook.

@rryman Please test.

**Comment by rsryman** [comment]
Thanks for all these updates, Arthur.

Looking forward to testing them whenever Robyn uploads the next version.
