### ISSUE TITLE
Stage Plan Puzzle Widget Should Have a "Start Over" Button

### ISSUE THREAD

**Issue by agryman** [rryman/BeneshForBalletBook4#44]
Add a button to reset the puzzle to its initial state. Use red text and button outline to match the styling in the rest of the book.

**Comment by agryman** [comment]
I added the "Start Over" button to the widget and updated the sample iBook.

@rryman Please test the new widget.

**Comment by rryman** [comment]
The new widget works great. Thank you very, very much!
As we discussed, the only issue is the information in the widget disappears if the user accidentally goes to another page. I will put a note in the instruction box to tell the user to be careful to stay on the page until they have completed the puzzle.
Thanks again. This is a fantastic addition to the book!

**Comment by agryman** [comment]
@rryman I'll create another issue to investigate if its possible to preserve the puzzle state.
