### ISSUE TITLE
Drag and Drop Doesn't Work in BMN Puzzle Widget on iPad

### ISSUE THREAD

**Issue by agryman** [rryman/BeneshForBalletBook4#45]
Drag and drop works in Safari using a mouse but doesn't work on iPad using touch. This is probably because the default iPad behavior is to scroll. The following links describe how to implement drag and drop on iOS.

Handling Events
https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/HandlingEvents/HandlingEvents.html

WebKit DOM Programming Topics: Dragging and Dropping
https://developer.apple.com/library/content/documentation/AppleApplications/Conceptual/SafariJSProgTopics/DragAndDrop.html

**Comment by agryman** [comment]
Probably better to do this using SVG instead of HTML. See:
http://www.petercollingridge.co.uk/interactive-svg-components/draggable-svg-element

**Comment by agryman** [comment]
My plan is to:
1) create the widget in SVG instead of HTML since we'll need to draw the puzzle and SVG gives you more control
2) create a simple SVG widget that let's you drag a circle using the mouse
3) modify the widget so that it also responds to touch events and verify that this works on an iPad
4) convert the BMN puzzle widget to SVG and handle touch events
5) allow the notation images to be dropped on eachother and automatically reflow

**Comment by agryman** [comment]
Found this article about using touch events with jQuery:
https://stackoverflow.com/questions/4755505/how-to-recognize-touch-events-using-jquery-in-safari-for-ipad-is-it-possible

**Comment by agryman** [comment]
The BMN puzzle is now working. Need to tweak the notation and eliminate the left and right whitespace so the bar lines overlap between the jigsaw pieces in the solution.

**Comment by agryman** [comment]
Comments from @rryman 

- Please remove the instructions from above the puzzle.
- Pieces 6 and 8 of the solved puzzle will have to be adjusted up one pixel when you implement the continuous stave solution.
- You are also going to implement local storage.

**Comment by agryman** [comment]
@rryman We should put to do's in the issue, not the PR. I copied your comments from the Pull Request(PR):

- **DONE**: Please remove the instructions from above the puzzle and add "Tap to activate." like Location Puzzle.
- Pieces 6 and 8 of the solved puzzle will have to be adjusted up one pixel when you implement the continuous stave solution.
- **DONE**: Draw a greyed out version of the puzzle piece in the storage box and always have a visual indication of where the piece will go in the solution box (insertion point).
- **DONE**: Freeze the solution - disallow drags.
- You are also going to implement local storage.
- Debug handle touch events.
- First bar of the puzzle in the storage box has an error. You said you will try to fix it editing the SVG. The Pulse Beat sign needs to be centred in the space between the other two positions and the jump line needs to start under the centre of the pulse beat. See bar 2 in the storage box for the correct position of the pulse beat and the start of the jump line.

**Comment by agryman** [comment]
@rryman fyi, I changed the insertion point to a rectangle and updated the Default.png.

**Comment by agryman** [comment]
@rryman The widget is done. Please test and close this issue.

**Comment by rryman** [comment]
I tested the puzzle it works great! Thanks a million!
