### ISSUE TITLE
Fix minor layout and text alignment errors in Stage Plan Puzzle Widget

### ISSUE THREAD

**Issue by agryman** [rryman/BeneshForBalletBook4#49]
Use constant spacing between columns in the stage plan. Use constant spacing between cells and anchor text to middle of cells. Align middle of cell with middle of location sign.

**Comment by agryman** [comment]
@rryman I fixed the alignment and created a new PNG. The widget is complete now. Please test.

**Comment by rryman** [comment]
Thanks. It works great! It looks beautiful :)

**Comment by rsryman** [comment]
Yes the puzzle look great and works very well, a great enhancement to the
book! Thanks, Dr. Ryman (Senior).
