### ISSUE TITLE
Sample Letters to Reviewers

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#5]
[ProofreaderGuidelinesBook3.docx](https://github.com/rryman/BeneshForBalletBook4/files/679671/ProofreaderGuidelinesBook3.docx)
[ProofreadingBook3Request.docx](https://github.com/rryman/BeneshForBalletBook4/files/679673/ProofreadingBook3Request.docx)

**Comment by rsryman** [comment]
[ReaderGuidelinesBook4.docx](https://github.com/rryman/BeneshForBalletBook4/files/1399764/ReaderGuidelinesBook4.docx)
[ReaderRequestBook4.docx](https://github.com/rryman/BeneshForBalletBook4/files/1399765/ReaderRequestBook4.docx)
