### ISSUE TITLE
Investigate if it's possible to preserve the state of HTML widgets when user scrolls to another page.

### ISSUE THREAD

**Issue by agryman** [rryman/BeneshForBalletBook4#51]
Native widgets can store state information. I'll see if its possible to do this for HTML widgets.

**Comment by agryman** [comment]
I found this article https://discussions.apple.com/message/17408275 which says it is possible to use the javascript localStorage object in iBooks.

**Comment by agryman** [comment]
@rryman please test.

**Comment by rryman** [comment]
Thank you! It worked when I embed the widget the second time through the "choose" option.

**Comment by agryman** [comment]
@rryman I corrected the centre alignment of the message. Please test.

**Comment by rryman** [comment]
I have tested this final version of the Widget. It works and looks great!
Thank you SO much xoxoxo...

**Comment by rryman** [comment]
It makes a wonderful addition to Book 4 :)

**Comment by agryman** [comment]
You're welcome. Glad to make a contribution to the book. Closing this issue. Now I'm working on drag and drop with touch gestures.
