### ISSUE TITLE
Guidelines for Book 4

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#6]
Suggested book content:
Stage Location and Travel (include diagonal travel?)
Ask Arthur to create Interactive Stage Plan as per OpenBenesh Website?
http://www.dancewrite.com/KingdomOfLocations/Interactive_Theory.html

Two parts to the book:
Part 1:
Theory and simple examples with runs, walks, bourrees, (sliding?) into poses.
Use RAD Solo Seal locations and travel as examples? Anuschka thinks this would be valuable.
Do we need to get permission from the RAD?
Anuschka suggests using circular travel paths as well.
Music or metronome?
If metronome play back at high volume to check for background noises.
Use ideas from http://www.dancewrite.com/KingdomOfLocations/Theory.html?
Don't link to OpenBenesh website as it is becoming increasingly difficult to update it.

Part 2:
Enchainements using the theory introduced in Part 1.
Use examples from published sources from different schools? (copyright issues)
Or only use generic enchainements?
Music?

Process:
Read theory in Benesh Encyclopedia first: http://164.39.188.53/
Send notation examples to Liz and Eliane in batches of 3 per page as we create them to get feedback as we go so we don't propagate errors?

**Comment by rsryman** [comment]
I thought it best to start the process by reading relevant parts of the Encyclopedia. 
I'll compile a file listing Chapters and Articles as I read them (sometimes only small excerpts are relevant) and upload the file, "iBook4outline.docx," when ready.

**Comment by rryman** [comment]
Thanks Sis. That will be very helpful!!!
In the meantime, I will scan the relevant chapters from Dance 341 and 474 and put the pdf's in GitHub.

**Comment by rryman** [comment]
How about we start a new Issue called "Resources for Book 4" and put all relevant documents into that thread?

**Comment by rryman** [comment]
Sis, I just experimented and it is possible to just copy the link from the Encyclopedia and paste it here into GitHub. Would that be more useful than creating a Word doc?

**Comment by rsryman** [comment]
Here is the in-progress word word doc in chart form so not done in github.
It does contain links from "Locations" on.

Can I create a chart in github?

**Comment by rryman** [comment]
I don't see the in-progess word doc here on GitHub. Did you drag the file to the GitHub message box?

**Comment by rsryman** [comment]
I didn't put it there. Can I still work on it in Word?

**Comment by rryman** [comment]
Yes, you can keep working on it in Word. Once you have completed the word doc you can drag it into GitHub.
