### ISSUE TITLE
Implement Travel Maze Puzzle

### ISSUE THREAD

**Issue by agryman** [rryman/BeneshForBalletBook4#65]
@rryman has provided 3 SVG files that describe a maze puzzle:
* BB111maze.svg - maze + path
* BB11maze2.svg - added pallette of four signs
* BB11maze3.svg - added pallette of buttons: Path Hint + Delete, Sign Hint + Delete

Add Javascript and package as a widget.

**Comment by agryman** [comment]
@rryman Please add the instructions to the student for solving the puzzle so I understand your intended user experience.

**Comment by agryman** [comment]
@rryman The widget is ready for testing. Please try it out.

**Comment by rryman** [comment]
Thank you very, very much! The widget works great. I am uploading the latest book to dropbox so Rhonda can try it out and give her input.

**Comment by rsryman** [comment]
Great! We’re out getting our flu shot. Looking forward to trying the maze puzzle when we get home.

**Comment by agryman** [comment]
@rryman You're welcome! Please close this issue if you are satisified.
