### ISSUE TITLE
Exporting Animations

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#7]
We discovered that the Sierra OS 10.12.2 causes .lfa files exported to QuickTIme to become pixelated.

Stop-gap solution to produce un-pixelated .mov files:
Rhonda to use her old MacBook Pro running OS 10.7.5 to export files.

Before starting Book 4, try to troubleshoot this issue.
Get Rhonda to compare all preference settings for QuickTime and LifeForms from old computer to new computer to see if there are any differences. Do this via Google Hangout with Rhonda sharing her screen with me?

**Comment by rsryman** [comment]
No answer still from Tom. I am creating all DanceForms animations on Jack's laptop, exporting to .m4v for Robyn to put into the .iba file.
