### ISSUE TITLE
Before Publishing

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#70]
Do a global search for:
_direction_ sign
_travel_ sign
_locomotion_ line
_movement_ line
_floor_ line?
_stage plan_
_qualification_ (_forward-right_; _forward-left_; _dot_; _stroke_?)
_repeat_ (_other side repeat_; _same side repeat_, etc.?)
_ad lib_
in front - or should it be in front?
_behind_ sign
_dot_
_general travel_ arrow?
_pulse beats_
_double brackets_
_starting bracket_
_ending bracket_
_stage location_ sign

sign (anything before it italicized if talking about a Benesh sign)
line (anything before it italicized if talking about a Benesh line)

courus or any ballet term - don't italicize
basic - don't italicize

Note: "find" no longer works well on our Book.
Gets stuck at the Review Questions - have to click on the page after the Review Questions to start find again.
It also gets stuck in pop-ups - not sure what to do about that one - read all pop-ups for correct italics?

**Comment by rsryman** [comment]
Do you want me to do this global search for you or with you via Hangout
(when you upload the latest Book4)?

**Comment by rryman** [comment]
I must have misunderstood. I thought you wanted me to create a GitHub entry of things we have to do when we have made all other edits (in case things change), just before sending the book to be reviewed?

**Comment by rsryman** [comment]
Right. These items are to be followed up before we send the Book to readers.
