### ISSUE TITLE
Metadata for BeneshForBallet Series for iBooks Store blurb

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#72]
**Description for Book 1**

﻿We all know what music scores look like. Have you ever wondered what dance scores look like, or if they even exist? There are in fact several dance notation systems and one of the most popular for ballet is Benesh Movement Notation (BMN). Like most languages, it is easier to read than it is to write. Reading basic ballet positions and movements is relatively simple.

This book introduces you to the fundamental concepts of BMN to help you read basic ballet positions from three "schools" of ballet: English, Italian, and Russian. The basic poses are described in words, images, and notated examples. Using interactive features, readers can add Highlights, take Notes, make Study Cards, and complete Reviews to learn BMN fundamentals while brushing up on ballet vocabulary.

**Description for Book 2**

We all know what music scores look like. Have you ever wondered what dance scores look like, or if they even exist? There are in fact several dance notation systems and one of the most popular for ballet is Benesh Movement Notation (BMN). Like most languages, it is easier to read than it is to write. Reading basic ballet positions and movements is relatively simple.

Rymans’ Benesh for Ballet series teaches you how to read BMN with words, images, animations, and notated examples. Using interactive features, readers can add Highlights, take Notes, make Study Cards, and complete Reviews to learn BMN theory while brushing up on ballet vocabulary and pedagogy.

Book 1 introduces you to the fundamental concepts of BMN. You'll learn to read basic ballet positions from three "schools" of ballet: English, Italian, and Russian. Book 2 continues with jumps without travel, so you can explore basic allegro steps and sequences timed to music.

**Description for Book 3**

Rymans’ Benesh for Ballet series teaches you how to read Benesh Movement Notation (BMN) using words, images, animations, and notated examples. The interactive features and reviews challenge you to learn BMN theory while brushing up on ballet vocabulary and pedagogy.

This is the third book in this series. Book 1 introduces the fundamental concepts of BMN. You'll learn to read basic ballet positions from three "schools" of ballet: English, Italian, and Russian. Book 2 presents the five basic categories of jumps so you can explore allegro steps and sequences without travel, timed to music. In Book 3 new BMN theory will prepare you to read notated examples of centre work and repeated sequences. You’ll explore how a basic dance phrase can be repeated in a variety of ways: the same, other side, alternating sides, or reverse. By reading phrases repeated with slight differences, you’ll learn to recognize the structure of a basic phrase and understand how it can be varied, which explains the term “ballet variation.”

**Comment by rryman** [comment]
First Draft
**Description for Book 4**

Rymans’ Benesh for Ballet series teaches you how to read Benesh Movement Notation (BMN) using words, images, animations, and notated examples. The interactive features and reviews challenge you to learn BMN theory while brushing up on ballet vocabulary and pedagogy.

This is the fourth book in this series. **_Book 1_** introduces the fundamental concepts of BMN. You'll learn to read basic ballet positions from three "schools" of ballet: English, Italian, and Russian. **_Book 2_** presents the five basic categories of jumps so you can explore allegro steps and sequences without travel, timed to music. **_Book 3_** prepares you to read notated examples of centre work and repeated sequences. By reading phrases repeated with slight differences, you’ll learn to recognize the structure of a basic phrase and understand how it can be varied. **_Book 4_** will not only be useful for ballet students and teachers, but also for dancers, choreographers, actors, stage managers, and theatrical stagers. The first three chapters contain new BMN theory for *stage plans* and also *location* and *travel* signs. The final two chapters build on theory covered in Books 1, 2, and 3 to present sequences with jumps, steps, and slides that travel around the performing area. *_Book 4_* contains DanceForms animations, interactive puzzles, and an extensive Glossary of definitions and cross-references used in Books 1-4, also making it a valuable resource for ballet students and teachers alike.

**Comment by rsryman** [comment]
Description for Book 4

Rymans’ Benesh for Ballet series teaches you how to read Benesh Movement Notation (BMN) using words, images, animations, and notated examples. The interactive features and reviews challenge you to learn BMN theory while brushing up on ballet vocabulary and pedagogy.

This is the fourth book in this series. **Book 1** introduces the fundamental concepts of BMN. You'll learn to read basic ballet positions from three "schools" of ballet: English, Italian, and Russian. **Book 2** presents the five basic categories of jumps so you can explore allegro steps and sequences without travel, timed to music. **Book 3** prepares you to read notated examples of centre work and repeated sequences. By reading phrases repeated with slight differences, you’ll learn to recognize the structure of a basic phrase and understand how it can be varied. **Book 4** focusses on sequences that travel around the performing area and is geared to dancers, choreographers, actors, stage managers, and theatrical stagers, as well as ballet students and teachers. No previous knowledge of BMN is needed to read first three chapters that introduce stage plans and also location and travel signs. The final two chapters build on theory covered in Books 1-3 by presenting sequences with jumps, steps, and slides that travel around the performing area. **Book** 4 also contains DanceForms animations, interactive puzzles, and an extensive Glossary of definitions and cross-references used in Books 1-4.

**Comment by rryman** [comment]
Arthur wants the information about Book 4 to be presented first, as he feels it gets lost. He suggested rearranging it. Do you agree with this version?

Rymans’ _Benesh for Ballet_ series teaches you how to read Benesh Movement Notation (BMN) using words, images, animations, and notated examples. The interactive features and reviews challenge you to learn BMN theory while brushing up on ballet vocabulary and pedagogy.

This is the fourth book in the series. **_Book 4_** focuses on sequences that travel around the performing area and is geared to dancers, choreographers, actors, stage managers, and theatrical stagers, as well as ballet students and teachers. No previous knowledge of BMN is needed to read the first three chapters that introduce stage plans and also location and travel signs. The final two chapters build on theory covered in _Books 1-3_ by presenting sequences with jumps, steps, and slides that travel around the performing area. _Book 4_ also contains DanceForms animations, interactive puzzles, and an extensive Glossary of definitions and cross-references used in _Books 1-4_.

_**Book 1**_ introduces the fundamental concepts of BMN. You'll learn to read basic ballet positions from three "schools" of ballet: English, Italian, and Russian. _**Book 2**_ presents the five basic categories of jumps so you can explore allegro steps and sequences without travel, timed to music. _**Book 3**_ prepares you to read notated examples of centre work and repeated sequences. By reading phrases repeated with slight differences, you’ll learn to recognize the structure of a basic phrase and understand how it can be varied.

**Comment by rryman** [comment]
Here's another thought ...

Rymans’ Benesh for Ballet series teaches you how to read Benesh Movement Notation (BMN) using words, images, animations, and notated examples. The interactive features and reviews challenge you to learn BMN theory while brushing up on ballet vocabulary and pedagogy.

This is the fourth book in the series. Book 4 focuses on sequences that travel around the performing area. No previous knowledge of BMN is needed to read the first three chapters that introduce stage plans and also location and travel signs. These chapters are relevant for dancers, choreographers, actors, stage managers, and theatrical stagers, as well as ballet students and teachers. The final two chapters build on theory covered in Books 1-3 by presenting sequences with jumps, steps, and slides that travel around the performing area, geared to ballet students and teachers. Book 4 also contains DanceForms animations, interactive puzzles, and an extensive Glossary of definitions and cross-references used in Books 1-4.

Book 1 introduces the fundamental concepts of BMN. You'll learn to read basic ballet positions from three "schools" of ballet: English, Italian, and Russian. Book 2 presents the five basic categories of jumps so you can explore allegro steps and sequences without travel, timed to music. Book 3 prepares you to read notated examples of centre work and repeated sequences. By reading phrases repeated with slight differences, you’ll learn to recognize the structure of a basic phrase and understand how it can be varied.

**Comment by rsryman** [comment]
Suggested revisions below in **bold** (so you can see what I have changed). Basically, we need to define the 3 "schools" sooner, and to end with some sort of summary sentence. Also, "relevant to" sounded too formal (para 2 line 3), and I don't mind that "geared to" is repeated (line 6), but we could also use "directed to" or "of particular interest to."

Rymans’ _Benesh for Ballet_ series teaches you how to read Benesh Movement Notation (BMN) using words, images, animations, and notated examples. The interactive features and reviews challenge you to learn BMN theory while brushing up on ballet vocabulary and pedagogy.

This is the fourth book in the series. **Book 4** focuses on sequences that travel around the performing area. No previous knowledge of BMN is needed to read the first three chapters that introduce stage plans and also location and travel signs. These chapters are **geared to** dancers, choreographers, actors, stage managers, and theatrical stagers, as well as ballet students and teachers. The final two chapters build on theory covered in Books 1-3 by presenting sequences with jumps, steps, and slides that travel around the performing area, geared to ballet students and teachers. Book 4 also contains DanceForms animations, interactive puzzles, and an extensive Glossary of definitions and cross-references of ballet terms from the three "schools" of ballet (English, Italian, and Russian) covered** in Books 1-4.

**Book 1** introduces the fundamental concepts of BMN. You'll learn to read basic ballet positions **of the feet, arms, and body, as performed in the three "schools."** **Book 2** presents the five basic categories of jumps so you can explore allegro steps and sequences without travel, timed to music. **Book 3** prepares you to read notated examples of centre work and repeated sequences. By reading phrases repeated with slight differences, you’ll learn to recognize the structure of a basic phrase and understand how it can be varied. **Book 4 caps the series by presenting challenging sequences that traverse the performing area.**

**Comment by rryman** [comment]
Thanks. I have made the revisions as suggested.
