### ISSUE TITLE
Sample Book 4

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#73]
I have uploaded SampleBeneshForBalletBook4.iba to DropBox "ForRhonda".

This is my first attempt at working out how much to give away in the sample book.
Please check it out:

1. Are there too many pages. If so which ones should I delete?
2. Have I deleted any pages you think I should have kept? If so which ones, and what pages should be deleted instead of them?
3. All the links that are relevant to the sample book should work. If they don't, which ones need to be corrected.
4. Glossary terms - Should we keep them all, delete them all, or just keep some as examples? If keeping some, which do you want to keep?

**Comment by rsryman** [comment]
Even this excerpt is quite substantial. I see how hard it is to pluck out a few pages and have it make sense. On the other hand, it should be a "teaser" and not have to stand alone as a teaching resource.
Maybe we could aim to take out a few pages: 5, 6, 7, 13, 14 ??
I wonder if we should include the maze on p. 19. On one hand it seems very generous to give it for free; on the other hand it might entice browsers to buy the book. If Arthur is OK I'm fine leaving it in.

**Comment by rryman** [comment]
If we take out pages 5, 6, and 7 and just leave in 8, won't it look like the first chapter is geared to ballet students and teachers and not to a more generic theatre group?

What about leaving in pages 5 and 6 and taking out 7 & 8?

I think we should go through this together via Google Hangout so it can be discussed. Easier than going back and forth via GitHub messages. Let me know when you are available.

**Comment by rsryman** [comment]
Good point. This afternoon is clear for me. What time is good for you?

**Comment by rsryman** [comment]
I’m just heading out to my cardio class. Tomorrow afternoon is fine.

Hope you get some advice and relief this afternoon.

Love, sis

**Comment by rryman** [comment]
Okay. Enjoy your class.

**Comment by rsryman** [comment]
Rhonda to check updates to:
- [ ] p. 11 alter bottom para re page ref
- [ ] p. 12  unbold performed from
- [ ] p. 13 change footnote
- [ ] p. 18 change footer; make sure this is the only music in the sample book
- [ ] Glossary: delete à terre entry
- [ ] In complete book unbold: p 23 performed from; p. 24 performed
- [ ] Rhonda to upload final Book 4 and synch to her iPad to send Robyn screen shots of the 5 slides: pp. 7, 19, 29, 30, 104
