### ISSUE TITLE
Slides for publishing Book 4

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#74]
Here are the 5 slides I chose. The last 3 slides all deal with forward travel. It shows the build up of the book. However, if you think there should be examples of travel in other directions let me know which pages you would rather I use.
![b4b4p7](https://user-images.githubusercontent.com/15850667/32444652-73b4c724-c2d1-11e7-90cd-80ae0dbe3520.jpeg)
![b4b4p19](https://user-images.githubusercontent.com/15850667/32444655-75077392-c2d1-11e7-8ecc-cab6f5945c72.jpeg)
![b4b4p29](https://user-images.githubusercontent.com/15850667/32444658-768da6c8-c2d1-11e7-806b-07e0e6c781c8.jpeg)
![b4b4p30](https://user-images.githubusercontent.com/15850667/32444664-79ca0c00-c2d1-11e7-8d07-3020c1b7e1b4.jpeg)
![b4b4p99](https://user-images.githubusercontent.com/15850667/32444668-7b17b36e-c2d1-11e7-9f8d-c3ca61b3550b.jpeg)

**Comment by rsryman** [comment]
These seem like good choices. Did you want intentionally include the Location Puzzle here instead of the Maze Puzzle from the sample book to entice browsers? The only alternative we might consider is using the same puzzle in the sample book and here, probably the Maze.

**Comment by rryman** [comment]
Arthur thinks we should keep in the maze puzzle in the sample book.
Don't you think it is more enticing to see a different puzzle in the slides?
Do you feel strongly about them only seeing one interactive puzzle? I guess
they can solve the Location Puzzle looking at the slide, but they can't do
it interactively without buying the book. Why do you think it should be the
same puzzle in the slides as in the sample book?
