### ISSUE TITLE
Ballet Music for Free

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#75]
Should we ever need ballet music in the future:
http://balletclassmusicforfree.com/new/index.php

**Comment by rsryman** [comment]
This looks promising, but my internet connection is acting up today -- very sluggish. I think we can download music to use for a ballet class but I doubt we can put it into a book we are selling, unless we contact Jefferson Dalby and make similar arrangements to Richard Maddock. As you say, for future consideration.

**Comment by rryman** [comment]
I agree. Permission would have to be obtained from Jefferson Dalby. Hopefully we won't need to change any music, but good to know there is another possible source.
