### ISSUE TITLE
Updates to Chapter 4 Section 2 - Curved Path of Travel and Brackets

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#76]
Based on Carla's feedback, below are the updated pages for this section.
![book4p54](https://user-images.githubusercontent.com/15850667/33807194-e4fb369a-dda0-11e7-9d14-785ca8a29bc0.jpeg)
![book4p55](https://user-images.githubusercontent.com/15850667/33807196-e6842404-dda0-11e7-9f76-6da692ce43b9.jpeg)
![book4p56](https://user-images.githubusercontent.com/15850667/33807197-e80d1628-dda0-11e7-87b5-8e4d11e5c4e4.jpeg)
![book4p57](https://user-images.githubusercontent.com/15850667/33807198-e966e54e-dda0-11e7-94be-9cdf90c21fc8.jpeg)
![book4p58](https://user-images.githubusercontent.com/15850667/33807199-eaaf8780-dda0-11e7-9f4d-1857348c8381.jpeg)
![book4p59](https://user-images.githubusercontent.com/15850667/33807215-231d6ae2-dda1-11e7-815f-cc59bd62d6ce.jpeg)

**Comment by rsryman** [comment]
This order works. 

Just for thought, in this order might it be more logical to start the dancer facing front on pp. 57-58?

**Comment by rryman** [comment]
If we have the dancers starting facing front on pp. 57-58 then the orientation of the curved travel signs will be different which I find more confusing. I was attempting to keep the shapes of the curved travel signs consistent.

If this orientation didn't bother you before with the previous order of the pages, then would you like me to reorder the pages to flow like they did before except with the two 1/2 circle pages first and then the two full circle pages?
i.e.,
Curved Paths Forward and Backward Travel - 1/2 Circle
Curved Paths Sideways Travel - 1/2 Circle
Curved Paths Forward and Backward Travel - Full Circle
Curved Paths Sideways Travel - Full Circle

I just found this order less appealing because it means the 3rd and 4th pages do not have any explanations.

**Comment by rsryman** [comment]
Yes, it would mean a lot of revising. I’m ok with keeping the same content
in the new order.

**Comment by rryman** [comment]
Please clarify what you mean by "new" order.

As per my recent update as shown in this GitHub entry, i.e.,:
Curved Paths Forward and Backward Travel - 1/2 Circle
Curved Paths Forward and Backward Travel - Full Circle
Curved Paths Sideways Travel - 1/2 Circle
Curved Paths Sideways Travel - Full Circle

Or a new order of:
Curved Paths Forward and Backward Travel - 1/2 Circle
Curved Paths Sideways Travel - 1/2 Circle
Curved Paths Forward and Backward Travel - Full Circle
Curved Paths Sideways Travel - Full Circle
(which will not have any explanations on the pages: "Curved Paths Forward and Backward Travel - Full Circle" and "Curved Paths Sideways Travel - Full Circle")

**Comment by rsryman** [comment]
I meant the order of your pages via GitHub.

**Comment by rryman** [comment]
Thanks!
