### ISSUE TITLE
Benesh for Ballet Flyer

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#77]
Updated metadata for Book 4

Rymans’ Benesh for Ballet series teaches you how to read Benesh Movement Notation (BMN) using words, images, animations, and notated examples. The interactive features and reviews challenge you to learn BMN theory while brushing up on ballet vocabulary and pedagogy.

This is the fourth book in the series. Book 4 focuses on sequences that travel around the performing area. No previous knowledge of BMN is needed to read the first three chapters that introduce stage plans and also location and travel signs. These chapters are geared to dancers, choreographers, actors, stage managers, and theatrical stagers, as well as ballet students and teachers. The final two chapters build on theory covered in Books 1-3 by presenting sequences with jumps, steps, and slides that travel around the performing area, geared to ballet students and teachers. Book 4 also contains DanceForms animations, interactive puzzles, and an extensive Glossary of definitions and cross-references of ballet terms from the three "schools" of ballet (English, Italian, and Russian) covered** in Books 1-4.

Book 1 introduces the fundamental concepts of BMN. You'll learn to read basic ballet positions of the feet, arms, and body, as performed in the three "schools." Book 2 presents the five basic categories of jumps so you can explore allegro steps and sequences without travel, timed to music. Book 3 prepares you to read notated examples of centre work and repeated sequences. By reading phrases repeated with slight differences, you’ll learn to recognize the structure of a basic phrase and understand how it can be varied. Book 4 caps the series by presenting challenging sequences that traverse the performing area.

**Comment by rryman** [comment]
[eBooksFlyerUpdated.pdf](https://github.com/rryman/BeneshForBalletBook4/files/1552527/eBooksFlyerUpdated.pdf)

**Comment by rryman** [comment]
[BeneshForBalletPostcard.pdf](https://github.com/rryman/BeneshForBalletBook4/files/1552528/BeneshForBalletPostcard.pdf)

**Comment by rryman** [comment]
Newly updated version for the release of Book 4.
[eBooksFlyerBook4.pdf](https://github.com/rryman/BeneshForBalletBook4/files/1566137/eBooksFlyerBook4.pdf)

**Comment by rryman** [comment]
Updated based on Rhonda's input.
[eBooksFlyerBook4.pdf](https://github.com/rryman/BeneshForBalletBook4/files/1566181/eBooksFlyerBook4.pdf)

**Comment by rryman** [comment]
"simply" removed. Updated Monday 18th December 2017.
[eBooksFlyerBook4.pdf](https://github.com/rryman/BeneshForBalletBook4/files/1568421/eBooksFlyerBook4.pdf)

**Comment by rsryman** [comment]
Rhonda to follow up re Book 4 publicity 1 week after publication (~Feb 10/18): 

If no word from Anna, use the version of the flyer without the RAD CPD sentence.
Check that Book 4 is available from the iTunes Store to make sure Apple has not taken it down, then announce its publication and attach flyer:

- [ ] Facebook pages: Benesh for Ballet, Global Benesh Community, Benesh International

- [ ] Benesh International: Benesh News & Event: https://www.rad.org.uk/study/Benesh/news-and-events; Benesh related news & events, email: beneshinstitute@rad.org.uk (address still valid?)

- [ ] Email announcement and flyer to  Bethany at RAD Canada and to our Reviewers, and ask them to spread the word: Liz Cunliffe, Eliane Mirzabekiantz, Anuschka Roes, Susanna Cheung, Rosalynd Elliott, Carla McGree-Eakin, Melanie Simpkin

- [ ] Email announcement and flyer to CORPS DE BALLET INTERNATIONAL, DCD, DNB, LODC, Nadia Potts, Susan Cohen, Natasha Frid, Carmen Duncan, Cindy Fisher, Laurie Westman, Susan Cash, Catherine Lee, Sang Mah, etc.

**Comment by rryman** [comment]
Saturday March 17th

I posted the jpeg of the flyer to:
Benesh for Ballet Facebook page
Global Benesh Community Facebook Group
Benesh International Facebook Group (post is pending approval)

I created a new Facebook Group for users of the ebook series to post their comments and questions:
Benesh for Ballet Facebook Group: https://www.facebook.com/groups/164751617560941/

**Comment by rryman** [comment]
Friday March 23rd I sent a request to Anna to add the jpeg of our latest flyer to her Benesh in Action Blog: https://beneshinaction.com/2015/02/09/new-release-benesh-ibook/

**Comment by rryman** [comment]
Monday March 26th:
1. Tweeted about Book 4.
2. Sent email to Sonia Briglio (sbriglio@radcanada.org) at RAD, cc'd Bethany Lifeso (blifeso@radcanada.org) and Clarke MacIntosh (cmacIntosh@radcanada.org) to ask Sonia if she would tweet about Book 4 via RAD Canada Twitter.

**Comment by rryman** [comment]
Monday March 26th:

RAD Canada tweeted about Book 4: https://twitter.com/RADCanada/status/978296664736792576
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Just released: Benesh for Ballet: Book 4! Available in the Apple iBooks Store! <a href="https://t.co/kpD4TGfiSr">https://t.co/kpD4TGfiSr</a></p>&mdash; RAD Canada (@RADCanada) <a href="https://twitter.com/RADCanada/status/978296664736792576?ref_src=twsrc%5Etfw">March 26, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by rryman** [comment]
![bforbtweet](https://user-images.githubusercontent.com/15850667/37930324-6c9c3258-3110-11e8-910f-4a5c02e198ea.jpeg)
