### ISSUE TITLE
Updates based on Reviewers Input

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#78]
Rhonda, I have uploaded the most recent version of the book (approx. 1:10 pm Thursday December 14th).

Below is the check list of most of the edits. I have not checked the latest version of the book yet. I plan to go through this list. You may want to do the same. Keeping track of all the linking was brain twisting, so I may have made some errors. As you suggested, once we have worked through this list and are satisfied with all the edits, I upload this version to DropBox for Ros to review for us given that we should be able to finish all this by Dec. 26th.

---
Pages Updated:
- [ ] iii - Chapter page numbers updated
- [ ] 6, 8, 9, 10, 11, 13, 14, 15, 30, 32, 34, 36, 38, 42, 45, 56, 57, 59, 60, 73, 76, 78, 79, 85, 94 (all links), 95, 96, 97, 104, 105, 106, 107, 108, 109, 110, 111, 119, 121, 122, 123, 124, 125, 126, 127, 128 - link and page number in footer
- [ ] 37 - content, links, and zoom
- [ ] 38 - content, footer link, and zoom
- [ ] 39 - content and zoom
- [ ] 46 - links to reviews for BB11
- [ ] 52 - content
- [ ] 53 - content
- [ ] 54 - content, links, zoom (please check the graphics carefully as I changed one)
- [ ] 55 - content and zoom
- [ ] 56 - content and zoom - footer text changed
- [ ] 57 - content and zoom - footer text changed
- [ ] 58 - content and zoom
- [ ] 55 -57 - does the content still make sense shifted around like this?
- [ ] 59 - footer added
- [ ] 63 - updated text and links to review questions
- [ ] 64 - Review 4.1 Questions 3 to 10
- [ ] 66 - Review 4.3 Questions 1 and 2
- [ ] 67 - Review 4.4 Questions 1 and 2
- [ ] 68 - Review 4.5 Questions 1 and 2
- [ ] 69 - Review 4.6 Questions 1 and 2
- [ ] 71 - Index links updated
- [ ] 72 - Jump line pop-up text editted
- [ ] 82 and 92 - link in text 
- [ ] 83 - Index links updated
- [ ] 89 - animation updated to eliminate the size discrepancy
- [ ] 90 - Index links updated
- [ ] 98 - updated links to review questions (These links are not updated on the version of the book presently being uploaded to DropBox. I have fixed them in my version of the book.)
- [ ] 112 - updated text and links to review questions
- [ ]  115 Review 6.3 New question
- [ ] 116 Review 6.4 New question
- [ ] 120 - Index links updated
- [ ] 129 - Index links updated
- [ ] 82, 92, 93, 94, 106, 107 - head in "i" boxes updated, either slightly, or fully were added where applicable.
- [ ] All links at the top of the review questions were changed - simplified to just a link back to the Review main pages - make sure I didn't miss any.
- [ ] Glossary - Jeté Ordinaire Derrière with Back Foot (English) updated
- [ ] Glossary - Retiré (English, Italian) updated

Also a couple of typos were fixed, but I didn't record them. There may be other things that Susanne and Melanie have in the word documents they sent us that I changed and didn't record here. I don't know if you feel it is necessary to go through those documents, to make sure I caught everything, as you check these changes. I will leave that up to you.

**Comment by rsryman** [comment]
I haven’t startedchecking the latest ibook yet,so I’ll connect with you
before I start work tomorrow in case you have a more recent version.

**Comment by rryman** [comment]
Text in bold are edits made based on Rhonda's input - Friday December 15th 2017

- [x] iii - Chapter page numbers updated
- [ ]   6, 8, 9, 10, 11, 13, 14, 15, 30, 32, 34, 36, 38, 42, 45, 56, 57, 59, 60, 73, 76, 78, 79, 85, 94 (all links), 95, 96, 97, 104, 105, 106, 107, 108, 109, 110, 111, 119, 121, 122, 123, 124, 125, 126, 127, 128 - link and page number in footer
- [x] 37 - content, links, and zoom
- [x] 38 - content, footer link, and zoom
- [x] 39 - content and zoom **(animation moved right so "left" is not cut off)**
- [x] 46 - links to reviews for BB11
- [x] 52 - content 
- [x] 53 - content **(text shifted down)**
- [x] 54 - content, links, zoom **(leaving as is, as out of context and therefore doesn't matter)**
- [x] 55 - content and zoom
- [x] 56 - content and zoom - footer text changed
- [x] 57 - content and zoom - footer text changed
- [x] 58 - content and zoom
- [x] 55 -57 - does the content still make sense shifted around like this?
- [x] 59 - footer added
- [x] 63 - updated text and links to review questions
- [x] 64 - Review 4.1 Questions 3 to 10
- [x] 66 - Review 4.3 Questions 1 and 2
- [x] 67 - Review 4.4 Questions 1 and 2
- [x] 68 - Review 4.5 Questions 1 and 2
- [x] 69 - Review 4.6 Questions 1 and 2
- [x] 71 - Index links updated
- [ ] 72 - Jump line pop-up text editted - **under discussion**
- [x] 82 and 92 - link in text
- [x] 83 - Index links updated
- [x] 89 - animation updated to eliminate the size discrepancy
- [x] 90 - Index links updated
- [ ] 96 - **Updated to "For curved paths of travel in other shapes see p. 59.**
- [x] 98 - updated links to review questions
- [x] 112 - updated text and links to review questions
- [x] 115 Review 6.3 New question
- [x] 116 Review 6.4 New question
- [x] 120 - Index links updated
    129 - Index links updated
    82, 92, 93, 94, 106, 107 - head in "i" boxes updated, either slightly, or fully were added where applicable.
    All links at the top of the review questions were changed - simplified to just a link back to the Review main pages - make sure I didn't miss any.
    Glossary - Jeté Ordinaire Derrière with Back Foot (English) updated
    Glossary - Retiré (English, Italian) updated

Also a couple of typos were fixed, but I didn't record them. There may be other things that Susanne and Melanie have in the word documents they sent us that I changed and didn't record here. I don't know if you feel it is necessary to go through those documents, to make sure I caught everything, as you check these changes. I will leave that up to you.

**Comment by rryman** [comment]
Further updates:

- [ ] Page 3 - Important: To hide the Playback Bar, tap the same place again as soon as the Play Button disappears.
- [ ] Page 20 - TIP: In this chapter the Playback Bar covers some of the animations. To hide the Playback Bar which appears when you tap the Play Button, tap again immediately in the same place.

**Comment by rsryman** [comment]
Continuing on from your original list (we still need to address the ones in
your first Dec 15 email):

  √82, 92, 93, 94, 106, 107 - head in "i" boxes updated, either slightly,
or fully were added where applicable.

  √All links at the top of the review questions were changed - simplified
to just a link back to the Review main pages - make sure I didn't miss any.

  √Glossary - Jeté Ordinaire Derrière with Back Foot (English) updated

  √Glossary - Retiré (English, Italian) updated



Also a couple of typos were fixed, but I didn't record them. There may be
other things that Susanne and Melanie have in the word documents they sent
us that I changed and didn't record here. I don't know if you feel it is
necessary to go through those documents, to make sure I caught everything,
as you check these changes. I will leave that up to you. I remember
checking the minor editorial and typo fixes as you made them. If/when I
have energy I may go through the original letters. Hopefully, our final
reviewers will catch any remaining errors – if we can upload this version
for Liz and Anuschka as well as Ros?



   - √  Page 3 - Important: To hide the Playback Bar, tap the same place
   again as soon as the Play Button disappears.
   - √  Page 20 - TIP: In this chapter the Playback Bar covers some of the
   animations. To hide the Playback Bar which appears when you tap the Play
   Button, tap again immediately in the same place.

**Comment by rsryman** [comment]
√ p. 39 *(animation moved right so "left" is not cut off)*

√ p. 53 *(text shifted down)*

√ p. 54  *(leaving as is, as out of context and therefore doesn't matter) *
Fine

√ p, 96 Updated to "For curved paths of travel in other shapes see p. 59.





Still to be checked:


p. 72 Jump line pop-up text editted - *under discussion*


I’m not sure what is needed here:

pp. 6, 8, 9, 10, 11, 13, 14, 15, 30, 32, 34, 36, 38, 42, 45, 56, 57, 59,
60, 73, 76, 78, 79, 85, 94 (all links), 95, 96, 97, 104, 105, 106, 107,
108, 109, 110, 111, 119, 121, 122, 123, 124, 125, 126, 127, 128 - link

**Comment by rryman** [comment]
Thanks, I have ticked these off in the new master list on GitHub.

**Comment by rryman** [comment]
Thanks. I have also ticked these off the master list on GitHub.

**Comment by rryman** [comment]
Here are the feedback documents from our Reviewers so far:
(I only copied the suggested edits from Carla. All her other comments were complementary in nature.)

[Book4Carla.docx](https://github.com/rryman/BeneshForBalletBook4/files/1568576/Book4Carla.docx)

[Book4Melanie.docx](https://github.com/rryman/BeneshForBalletBook4/files/1568577/Book4Melanie.docx)

[Book4Susan.docx](https://github.com/rryman/BeneshForBalletBook4/files/1568578/Book4Susan.docx)

**Comment by rryman** [comment]
December 18th - more links I missed and failed to update!
- [ ] Page 94 - FYI - page number and link updated
- [ ] Page 121 - FYI - pp. 114-117 changed to pp. 121-124

**Comment by rsryman** [comment]
I have gone through the comments from Carla, Melanie, and Susanne. All good. 

The only thing I noticed was re p. 61 in the first footnote we need a full stop (.) after Simpkin, yes?
