### ISSUE TITLE
Completed Tasks Based on Input from Liz, Ros, and Anuschka

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#82]
Below is a list of tasks completed by Robyn with page numbers.

- [x] p. 1: Changed 9 pt space to 18 pt space before the bulleted list to help user find sweet spot on top link (and refine layout as needed).
___
p.5:
 - [x] Changed 9 pt space to 18 pt space before the bulleted list to help user find sweet spot on top link (and refined layout as needed).
 - [x] Updated text "Reviews for Benesh Basics 10" and relinked it.
 - [x] Updated page name so the Table of Contents (pinch two fingers together) has the correct name as well.
___
 - [x] p.7: Changed 9 pt space to 18 pt space before the bulleted list to help user find sweet spot on top link (and refined layout as needed).
- [x] p. 12: Updated Anna jpeg to look more angled. Image doesn't zoom.
___
p. 13:
- [x] updated Anna jpeg to look more angled. Image doesn't zoom.
- [x] Deleted the word "room" from "room numbering system"; and redid link to p. 125.
___
- [x] p. 14: Updated Anna jpeg to look more angled. Image doesn't zoom.
- [x] p. 16: Updated 3 notation examples with arms level by sides so the level signs are in the centre of the waist and knee line. This notation should zoom. (I did a screen shot of the page and sent it to Liz to clarify her issue with the costuming of the DanceForms figures and she approved it.)
___
p. 17:
- [x] Changed heading to: Reviews for BB10.
- [x] Updated Intro text - check for accuracy.
- [x] Added TIP at bottom of page. (I emailed Liz to thank her for her comment, sent a screen shot, and told her that we added this Tip so she will know how to drag the labels when she downloads the published book with her promo code.)
___
- [x]  p. 18: Changed text after Review 2.1 heading.
- [x] p. 19: Changed text after Review 2.2 heading.
___
p. 20:
- [x] Changed 9 pt space to 18 pt space before the bulleted list to help user find sweet spot on top link (and refine layout as needed).
 - [x] Updated text "Reviews for Benesh Basics 11" and relinked it.
 - [x] Updated page name so the Table of Contents (pinch two fingers together) has the correct name as well.
- [x] Added "These animations are done in silence." to Tip box.
____
- [x] p. 21: Text added to the bottom of the page: Each _general travel_ sign is the basis for four basic travel signs which incorporate both the **path** and the **direction faced** during travel, as explained on the next page.
- [x] p. 22: Changed 9 pt space to 18 pt space before the bulleted list to help user find sweet spot on top link (and refine layout as needed).
- [x] p. 29: FYI added - check text and position of open pop-up window.
- [x] p. 30: Enlarged travel arrows by 120% below left stage plans and composite location and summary travel signs below right stage plans. Both images should zoom. **Do they look okay?**
- [x] p. 32: Enlarged travel arrows by 120% below left stage plans and composite location and summary travel signs below right stage plans. Both images should zoom. **Do they look okay?**
- [x] p. 34: Enlarged travel arrows by 120% below left stage plans and composite location and summary travel signs below right stage plans. Both images should zoom. **Do they look okay?**
- [x] p. 36: Enlarged travel arrows by 120% below left stage plans and composite location and summary travel signs below right stage plans. Both images should zoom. **Do they look okay?**
- [x] p. 37: Changed 9 pt space to 18 pt space before the bulleted list to help user find sweet spot on top link (and refine layout as needed).
- [x] p. 39: Replaced both animations with Rhonda's corrected arm version.
- [x] p. 40: Cropped in iPhoto and replaced 4 images - images do not zoom when tapped.
The vertical and horizontal placement is very tricky on this page. I wan't sure what to align with what. Does it look okay as is, or do you have a better suggestion?
___
p. 41:
- [x] Replaced 4 animations with Rhonda's corrected arm version.
- [x] Deleted asterisk after "throughout."
___
- [x] p. 42: Enlarged travel arrows by 120% below left stage plans and composite location and summary travel signs below right stage plans. Both images should zoom. **Do they look okay?**
- [x] p. 43: Cropped in iPhoto and replaced 4 images - images do not zoom when tapped.
The vertical and horizontal placement is very tricky on this page. I wan't sure what to align with what. I know you had suggested aligning the arm with the forward and backward travel signs, but that creates odd spacing. Do you still want me to do that?
___
p. 44:
- [x] Replaced 4 animations with Rhonda's corrected arm version.
- [x] Deleted asterisk after "throughout."
- [x] I did a global search to see if there were matching pairs. Have I missed any?
___
- [x] p. 45: Enlarged travel arrows by 120% below left stage plans and composite location and summary travel signs below right stage plans. Both images should zoom. **Do they look okay?**
___
p. 46:
- [x] Changed heading to: Reviews for BB11.
- [x] Updated Intro text.
- [x] Added TIP at bottom of page.
___
p. 47:
- [x] Changed text after Review 3.1 heading.
- [x] Questions 8 & 9 lightened the vertical dotted black lines on the stage plan and thickened the  blue travel arrow. Does this look okay?
___
- [x]  p. 48: Changed text after Review 3.2 heading.
- [x]  p. 49: Changed text after Review 3.3 heading.
- [x]  p. 50: Changed text after Review 3.4 heading.
___
p. 51:
 - [x] Changed 9 pt space to 18 pt space before the bulleted list to help user find sweet spot on top link (and refined layout as needed).
 - [x] Updated text "Reviews for Benesh Basics 12" and relinked it.
 - [x] Updated page name so the Table of Contents (pinch two fingers together) has the correct name as well.
___
- [x] p. 54: Changed 9 pt space to 18 pt space before bulleted list to help user find sweet spot on top link (and refine layout as needed).
___
p. 63:
- [x] Changed heading to: Reviews for BB12.
- [x] Updated Intro text. This changed the links to the reviews so they need to be checked.
- [x] Added TIP at bottom of page.
___
- [x]  p. 64: Changed text after Review 4.1 heading.
- [x]  p. 65: Changed text after Review 4.2 heading.
___
p. 66:
- [x] Changed text after Review 4.3 heading.
- [x] Added labels - Animation for Question 1 and Animation for Question 2.
I had to change size of animations and realign them. Check they look okay.
___
p. 67:
- [x] Changed text after Review 4.4 heading.
- [x] Added labels - Animation for Question 1 and Animation for Question 2.
I had to change size of animations and realign them. Check they look okay.
___
p. 68:
- [x] Changed text after Review 4.5 heading.
- [x] Added labels - Animation for Question 1 and Animation for Question 2.
I had to change size of animations and realign them. Check they look okay.
___
p. 69:
- [x] Changed text after Review 4.6 heading.
- [x] Added labels - Animation for Question 1 and Animation for Question 2.
I had to change size of animations and realign them. Check they look okay.
___
p. 70:
 - [x] Changed 9 pt space to 18 pt space before the bulleted list to help user find sweet spot on top link (and refined layout as needed).
 - [x] Updated text "Reviews for Benesh Basics 13" and relinked it.
 - [x] Updated page name so the Table of Contents (pinch two fingers together) has the correct name as well.
- [x] Changed beginning of footer "The music excerpts starting on p. 78 ...".
___
- [x] p. 71: Changed 9 pt space to 18 pt space before the bulleted list to help user find sweet spot on top link (and refine layout as needed).
- [x] p. 78: Colon instead of full stop after "Count" in  iBox (Anacrusis and Bars).
- [x] p. 79: Colon instead of full stop after "Count" in  iBox (Anacrusis and Bars).
- [x] p. 82: Colon instead of full stop after "Count" in  iBox (Anacrusis and Bars).
___
p. 83:
 - [x] Changed 9 pt space to 18 pt space before the bulleted list to help user find sweet spot on top link (and refined layout as needed).
 - [x] Updated notation examples with arms level by sides so the level sign is in the centre of the waist and knee line. This notation should zoom.
___
- [x] p. 85: Updated notation examples with arms level by sides so the level sign is in the centre of the waist and knee line. This notation should zoom. 
- [x] p. 90: Changed 9 pt space to 18 pt space before the bulleted list to help user find sweet spot on top link (and refine layout as needed).
- [x] p. 92: Colon instead of full stop after "Count" in  iBox (Anacrusis and Bars).
- [x] p. 93: Colon instead of full stop after "Count" in  iBox (Anacrusis and Bars).
- [x] p. 94: Colon instead of full stop after "Count" in  iBox (Anacrusis and Bars).
- [x] p. 97: Colon instead of full stop after "Count" in  iBox (Anacrusis and Bars).
___
p. 98:
- [x] Changed heading to: Reviews for BB13.
- [x] Updated Intro text. This changed the links to the reviews so they need to be checked.
- [x] Updated text for Review 5.1  from "eight" questions -> "eleven" question.
- [x] Added TIP at bottom of page.
___
p. 99:
- [x] Changed text after Review 5.1 heading.
- [x] p. 99 Q 5 of 11 updated instructions: "…on each couru sequence."
- [x] p. 99: Old Question 7 has been broken into 4 multiple choice questions with larger BMN staves; on 4th example changed right foot step into 2nd to left foot. I sent screen shots to Ros and Anuschka and they were both happy with this solution.
___
- [x]  p. 100: Changed text after Review 5.2 heading.
- [x]  p. 101: Changed text after Review 5.3 heading.
- [x]  p. 102: Changed text after Review 5.4 heading.
___
p. 103:
 - [x] Changed 9 pt space to 18 pt space before the bulleted list to help user find sweet spot on top link (and refined layout as needed).
 - [x] Updated text "Reviews for Travelled Sequences" and relinked it.
 - [x] Updated page name so the Table of Contents (pinch two fingers together) has the correct name as well.
___
p. 104:
- [x]  Added to the i-box text: The dancer performs a series…rectangular pattern: three toward downstage, four toward stage right, three toward upstage, and four toward stage left.
- [x] Added FYI - check text.
- [x] Colon instead of full stop after "Count" in  iBox (Anacrusis and Bars).
___
- [x] p. 105: Updated notation examples with arms level by sides so the level sign is in the centre of the waist and knee line. Both notation staves should zoom.
- [x] p. 106: Colon instead of full stop after "Count" in  iBox (Anacrusis and Bars).
___
p. 107
- [x] Colon instead of full stop after "Count" in  iBox (Anacrusis and Bars).
- [x] Updated animation.
___
- [x] p. 108: Colon instead of full stop after "Count" in  iBox (Anacrusis and Bars).
- [x] p. 110: Colon instead of full stop after "Count" in  iBox (Anacrusis and Bars).
**Have I missed any periods that should be colons in any of the iBoxes in the book?**
___
p. 112:
- [x] Changed heading to: Reviews for Travelled Sequences.
- [x] Updated Intro text. This changed the links to the reviews so they need to be checked.
- [x] Added TIP at bottom of page.
___
p.  113:
- [x]  Changed text after Review 6.1 heading.
- [x] Q3 & Q4: Updated notation examples with arms level by sides so the level sign is in the centre of the waist and knee line. This notation should zoom.
- [x] **Did I miss any examples in the book with arms by sides?**
- [x] Q 14: Moved 3rd button a bit to the right under the diagonal cross-out sign
___
- [x]  p. 114: Changed text after Review 6.2 heading.
- [x]  p. 115: Changed text after Review 6.3 heading.
___
p. 116:
- [x]  Changed text after Review 6.4 heading.
- [x]  Updated both animations.
___
- [x]  p. 117: Changed text after Review 6.5 heading.
___
p. 118
 - [x] Changed 9 pt space to 18 pt space before the bulleted list to help user find sweet spot on top link (and refined layout as needed).
- [x] Deleted the word "room" from "direction signs and room numbering"; and redid link.
___
- [x]  p. 120: Changed 9 pt space to 18 pt space before the bulleted list to help user find sweet spot on top link (and refine layout as needed).
- [x] pp. 125 deleted the word "room" from Title; and updated page name so the Table of Contents (pinch two fingers together) has the correct name as well.
- [x]  p. 129: Changed 9 pt space to 18 pt space before the bulleted list to help user find sweet spot on top link (and refine layout as needed).
- [x]  p. 132: Changed 9 pt space to 18 pt space before the bulleted list to help user find sweet spot on top link (and refine layout as needed).

**Comment by rryman** [comment]
Still to be completed:
- [ ] p. 97: Put in updated notation once approved by Liz.
- [ ] p. 98: Put in updated notation once approved by Liz.

**Comment by rsryman** [comment]
- [ ] p.17 Small point re TIP: To be consistent with the para above, should we say "in these Review questions" versus "in these review questions" versus "in these Reviews"? Same re pp. 46, 63, 98, 112.

- [ ] p. 18 I see that there is room at the top, and since this is the first review with multiple questions, should we say: Tap the red right arrow for the next question or the left red arrow for the previous question. There is room so perhaps also add on pp. 47, 64, 99, 113

- [ ] pp. 21-22, etc. Re "direction faced" do a global search for consistency in use of bold (p. 21 **direction faced**; p. 22 **direction** faced; etc.). We could use **direction faced** on the pages where we introduce new theory (pp. 21, 22, 33, 35) but plain text on the rest? Maybe **direction faced** on p. 47 for emphasis?

- [ ] p. 22 (separate text boxes but no 18pt carriage return, although there is plenty of room).

- [ ] p. 42 In the zoomed left image top middle stage plan, I notice that the shaft and forward tick are a different angle in the plan versus below it. Because the in-plan sign is "analog" but the below plan sign is "digital, or to prevent the tick from being superimposed on the dotted vertical line? Not a problem on the 3 other diagonal travel signs.

- [ ] p. 43 The far left dancer isn't aligned with the right 3 dancers. I checked and it seems possible to move the far left dancer upward a bit and the 3 others downward to align their feet, as on p. 40.

- [ ] p. 44 Don't know what you mean by "matched pair." Other places to put the updated 2 animations?

- [ ] p. 46 See comment re p. 17

- [ ] p. 47 See comment re p. 18

- [ ] p. 63 See comment re p. 17

- [ ] p. 64 See comment re p. 18

- [ ] p. 83 layout looks a bit "top heavy" - move staves down a bit?

- [ ] p. 94 no Anacrusis?

COMPLETED TO HERE

- [ ] p. 98 See comment re p. 17

- [ ] p. 99 See comment re p. 18

- [ ] p. 112 See comment re p. 17

- [ ] p. 113 See comment re p. 18

- [ ] RE WORKSHEETS: Rhonda to make note to update all MacBenesh where hands hang beside thighs (level sign at centre of 2nd space).

- [ ] Rhonda to update Grand Jeté in review re music (add silence at start) & refine timing.

**Comment by rsryman** [comment]
- [ ] p. 98 capitalization of "Review" only when specific numbers, all others in lower case

- [ ] p. 102 Rhonda to update Grand Jeté in review re music (add silence at start) & refine timing.

- [ ] p. 113 Q3&4 the notation can be pinched out but does NOT zoom; I looked through the entire book and found stave notation of hands hanging on pp. 16, 83, 85, 105 -- all correct

- [ ] RE WORKSHEETS: Rhonda to make note to update all MacBenesh where hands hang beside thighs (level sign at vertical & horizontal centre of 2nd space) re pp. 16, 83, 85, 105, 113 Q3&4

**Comment by rryman** [comment]
Rhonda:
p. 113 Q3&4 the notation can be pinched out but does NOT zoom; 

Robyn:
- [ ] Sorry ... I simply copied and pasted from p. 105 comment and forgot to delete the zoom information. Unfortunately, notation in the Review Widget can't zoom and can only be pinched out.
Please tick this when you have read this comment.

**Comment by rsryman** [comment]
That's what I thought, just checking.
