### ISSUE TITLE
Completed Tasks Based on Rhonda's Proofreading of Updates from Ros, Liz, and Anuschka

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#83]
- [x] p. ii: To verify theoretical information we consulted the _Benesh Encyclopaedia_. This online resource is published by Benesh International (formerly The Benesh Institute) at the Royal Academy of Dance (RAD) and is currently available to members only.
- [x] p. 4: bolded "direction faced".
___
p.17: 
- [x] Updated text - all "reviews" have lower case "r", except when it is a name that is linked, i.e., Review 2.1.
- [x] Updated tip to read:
"TIP: To drag labels to buttons in the reviews, tap and HOLD until the label activates before you move it."
___
- [x] p. 18: Updated heading - "Tap the red right arrow for the next question or the left red arrow for the previous question." 
___
p. 21: 
- [x] Bolded "direction faced".
- [x] Bolded "path of travel".
___
p. 22:
- [x] Bolded "direction faced".
- [x] Bolded "path of travel".
- [x] Moved bulleted list to try to mimic 18pt gap.
___
- [x] p. 23: Bolded "direction faced".
- [x] p. 33: Bolded "direction faced".
- [x] p. 35: Bolded "direction faced".
- [x] p. 42: Updated the shafts and forward ticks in the plan to try to match the below plan travel signs.
- [x] p. 43: Reformatted page so toes of DanceForms figures are lined up.
___
p. 46:
- [x] Updated text - lower case r's.
- [x] Updated tip.
___
p.47: 
- [x] Updated text in heading.
- [x] Q2. - Bolded "direction faced".
___
p. 63:
- [x] Updated text - lower case r's.
- [x] Updated tip.
___
- [x] p. 64: Updated text in heading.
- [x] p. 83: Updated placement of the two notation examples. No change to the ending double bar lines. They are remaining different.
- [x] p. 93: Took out bolding "clarify the" and "specify the".
___
p. 98:
- [x] Updated text - lower case r's.
- [x] Updated tip.
___
- [x] p. 99: Updated text in heading.
- [x] p. 102: Updated animation.
- [x] p. 93: Took out bolding "overall".
___
 p. 112:
- [x] Updated text - lower case r's.
- [x] Updated tip.
___
p. 113: 
- [x] Updated text in heading.
- [x] Q7 - made "zig zag" one word "zigzag".

**Comment by rryman** [comment]
Still to be completed by Robyn:
- [ ] p. 97: Put in updated notation once approved by Liz.
- [ ] p. 98: Put in updated notation once approved by Liz.
- [ ] p. 102: Put in updated notation once approved by Liz.

**Comment by rsryman** [comment]
- [ ] p. 18, 47, 64, 99, 113 Should we update top line re word order to be consistent?
"red right arrow" & "red left arrow" or " right red arrow" & "left red arrow" (your choice)

- [ ] p. 93: Took out bolding "overall". Done but on p. 103

**Comment by rryman** [comment]
Completed by Robyn. To be checked by Rhonda.

- [ ] pp. ii and 130: Updated Benesh International and the link.

- [ ] pp. 18, 47, 64, 99, 113 Should we update top line re word order to be consistent?
 " right red arrow" & "left red arrow"

**Comment by rryman** [comment]
Still to be completed by Robyn:
- [ ] Cover and Intro Media - BI and RAD logo?
- [ ] pp. ii and 130: If necessary, update the link to Benesh International. Waiting on email from Anna.
- [ ] p. 97: Put in updated notation once decided.
- [ ] p. 98: Put in updated notation once decided.
- [ ] p. 102: Put in updated notation once decided.

**Comment by rryman** [comment]
- [ ] p. 97 - added pop-up. To be approved by Rhonda and wordsmithed as necessary.

Rhonda, in Book 3 (i.e., p. 52) we use the concept of showing the different transition after the repeat sign,  but do not really explain it anywhere. We do explain the use of notation in the empty bars in Book 3 on p. 64, but this is a different context.

Given that Canan had issues with it in the example in Book 4, I think it is a good idea to clarify this theory. Do you agree? See attached jpeg.
![page97](https://user-images.githubusercontent.com/15850667/35196762-661ce4d4-fea4-11e7-8610-c0b75c4c1362.jpeg)

**Comment by rryman** [comment]
- [ ] Robyn will update pages 98 and 102 when confirmation is received from Liz.

- [ ] In the meantime, Robyn has updated page 97 with the latest version of the notation and the pop-up. If this changes based on feedback from Liz, Robyn will update page 97 accordingly.
![book4page97](https://user-images.githubusercontent.com/15850667/35225138-7c642bd8-ff55-11e7-97b7-1ffb46921eea.jpeg)
![book4page97b](https://user-images.githubusercontent.com/15850667/35225144-7e8027fa-ff55-11e7-9b4f-f86dd421c231.jpeg)

**Comment by rsryman** [comment]
Suggested wording for popup re the use of "Prep." on p. 97: 

In silence before the music begins on Bar 1 count 1, the dancer performs a preparatory run. For clarification the word _Prep._ written above the run shows where the preparation begins and the closing bracket indicates where the preparation ends. OR For clarification the word _Prep._ is written above the run to show where the preparation begins and the closing bracket is added to show where the preparation ends. 

Re sentence 1, I remember that we tried to consistently start by stating a Bar number, but this examples might warrant an exception since it is about something that happens before a Bar number?: In this example, the dancer performs a preparatory run in silence, before the music begins on Bar 1 count 1.…

**Comment by rryman** [comment]
Yes, I tried to start with Bar number for consistency, but as you don't think it is necessary then I prefer the following. Are you okay with the updated text below? 

In the notation above, the dancer performs a preparatory run in silence, before the music begins on Bar 1 count 1. For clarification the word _Prep_. is written above the stave to show where the preparation begins and the _closing bracket_ is added to show where the preparation ends.

**Comment by rryman** [comment]
Should we say something about the run being "in tempo"?

**Comment by rsryman** [comment]
You are referring to the point made in Monica's book p. 25? Technically if
we added "in tempo" (as below) we have to move the word "Waltz" to Bar 1.

In the notation above, the dancer performs a preparatory run in silence (in
tempo), before the music begins on Bar 1 count 1. For clarification the
word *Prep*. is written above the stave to show where the preparation
begins and the *closing bracket* is added to show where the preparation
ends.

Better to leave as is, in your version of 2:33 pm.

**Comment by rsryman** [comment]
Further to Robyn's update, the Benesh Encyclopaedia has superceeded the
theory in Monica's book p. 25. We will use:

In the notation above, the dancer performs a preparatory run in silence (in
tempo), before the music begins on Bar 1 count 1. For clarification the
word *Prep*. is written above the stave to show where the preparation
begins and the *closing bracket* is added to show where the preparation
ends.

**Comment by rryman** [comment]
Completed by Robyn. To be checked by Rhonda.

- [ ] pp. ii and 130: Updated Benesh International and the link.
- [ ] pp. 18, 47, 64, 99, 113 Should we update top line re word order to be consistent?
    " right red arrow" & "left red arrow"
 - [ ] p. 97: Updated notation (notation should zoom). Added two pop-ups. Updated "iBox" (In Silence, and landing location before run off stage.
 - [ ] p. 98: Updated notation (notation should zoom).
 - [ ] p. 102: Updated notation (notation should zoom). I had to fiddle with the notation on the left to make it the same width as the notation on the right. Did I mess anything up?

**Comment by rsryman** [comment]
- [ ] p. 97 For consistent wording in the popup vs i-box text "Prep" vs "In silence" and "run" vs "leap," I suggest (with underline of "Count 3 (in silence):"):

**Preparation.** Count 3 (in silence): Leap (run) forward onto right foot.

**Comment by rryman** [comment]
Rhonda, I tried calling but couldn't get through because of "technical difficulties".

Wording for page 102:

Comma needed? Which do you prefer? Or do you want something different.
Keep format similar to other footnotes - i.e., page last?

For an enlarged view of the notation above left, see p. 97.
For an enlarged view of the notation above right, see p. 98.

For a larger version of the notation above left, see p. 97.
For a larger version of the notation above right, see p. 98.

**Comment by rsryman** [comment]
I prefer: 
For a larger version of the notation above left, see p. 97.
For a larger version of the notation above right, see p. 98.

**Comment by rryman** [comment]
Sending updated version of Book 4 to DropBox now:
- [ ] p. 97: iBox Updated.
- [ ] p. 102: 2 footnotes added.

**Comment by rryman** [comment]
Oh Crap! You can never just make one change without it causing an inconsistency!!!
I will have to find a way to link to page 102 from page 97 and 98 to be consistent re reciprocal links.
Don't bother downloading the updated book yet!!! ;( ;( ;(

**Comment by rsryman** [comment]
Maybe just don't link to pages 97 and 98, just leave as a note? They can
get there in a few swipes.

**Comment by rryman** [comment]
- [ ] p. 97: iBox Updated. Footnote added with link.
- [ ] p. 98: Footnote added with link.
- [ ] p. 102: 2 footnotes added with links.
