### ISSUE TITLE
Final Edits for Book 4

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#84]
p. ii: 
- [x] Updated DanceForms link to:
http://www.credo-interactive.com/products/danceforms/
- [x] Updated Richard Maddock's website link to:
http://www.richardmaddock.com/music.html
___
- [x]  p. 4: Updated third sentence in first paragraph.
Even though BMN provides specific terminology for location signs, notators describe locations in terms familiar to dancers.
- [x]  p. 14: Times Roman text removed from expanded text box. All notation should zoom. Hopefully no new errors were introduced.
- [x]  p. 39: Updated footnote: This explanation is based on…
 - [x] p. 56: Added hyphen to below-stave. 
 - [x] p. 57: Added hyphen to below-stave. 
- [x] p. 59: Updated twice: figure eight pattern. Added hyphen to below-stave. 
 - [x] p. 90: Updated In-Stave. Added hyphen to Below-Stave.  Links should still work. 
 - [x] p. 96: i-box text, updated twice: figure eight pattern 
 - [x] p. 97: Added hyphen to below-stave. 
 - [x] p. 101: Added hyphen to below-stave. 
 - [x] p. 113 Q. 1, 3, and 5: Added hyphen to below-stave. 
___
p. 133:
- [x] Updated Ballet Moves II link to:
http://www.credo-interactive.com/products/danceforms/
- [x] Took out the word "Institute" where applicable. 
- [x] Added capital T to The Benesh Institute.
- [x] Took out (see Sources) as Rhonda's sources are now displayed on two pages instead of one.
___
- [ ] p. 134: Took out the word "Institute" where applicable.

**Comment by rsryman** [comment]
- [ ] p. 39 update note at bottom: This explanation is based on…

 [ ] pp. 59, 96 i-box text, update twice on each page: figure eight pattern

**Comment by rsryman** [comment]
- [ ] GLOBAL EDIT: We consistently use a hyphen for "in-stave information" but I noticed inconsistency re "below-stave information" (pp. 93, 103) versus "below stave information" (pp. 56, 57, 59, 90, 97, 101, 113 Q 1+3+5). I think we should be suing the hyphen for a compund adjective. Also inconsistent use of upper vs lower case on p. 90 linked list re "In-stave" versus "Below Stave" (should be In-Stave and Below-Stave ??); hyphenation is correct on the linked headings of pp. 92, 93. We can update this together by Hangout if you like.

I checked links in FIY windows (only found on pp. 32-94√), completed all Reviews√, and tested the Interactive Stage Plans (pp. 121-125)√

Just two suggested edits in the wording/punctuation of 2 review questions:

- [ ] p. 99: Q 5 of 11: Suggested update ("appropriate" or "feasible"?) cf p. 113 Q 10:
Drag the travel sign to match the feasible direction of travel on each couru sequence.

- [ ] p. 113 Q 1+3+5 of 14 no commas needed

**Comment by rsryman** [comment]
- [ ] p. 4 Update para 1 sentence 3 CURRENT: Though BMN uses specific terminology for location signs, when working with dancers notators use the terms with which dancers are familiar.

SUGGESTED:
Even though BMN provides specific terminology for _location_ signs, notators use whatever lay terms are most familiar to dancers.
OR
Even though BMN provides specific terminology for _location_ signs, notators describe locations in terms familiar to dancers.

**Comment by rsryman** [comment]
All good, except for two minor items:

- [ ] p. 4 Add italics (cf bottom of p. 4: italics for _travel_ signs):  
Even though BMN provides specific terminology for _location_ signs, notators describe locations in terms familiar to dancers.

- [ ] p. 143 I read your bio and questioned the "s" at the end of "Bayerisches Staatsballett" so I looked it up online and found "Bayerische Staatsoper" -- different name today than 1980's? Maybe you should verify the official name and spelling. 
It also occurred to me that we usually refer to a choreographic works as you do re Macdonald and Nureyev, but perhaps you wanted a less repetitive wording, -- your choice re:
She has reconstructed Lynne Seymour's _Intimate Letters_, and Sir Frederick Aston's _Les Patineurs_ and _Façade_, and has…

**Comment by rryman** [comment]
- [ ] p. 4: Added italics to _location_ signs.
- [ ] p. 134: Edited text to -
She has reconstructed Lynne Seymour’s _Intimate Letters_, Sir Frederick Aston’s _Les Patineurs_ and _Façade_, and has served as rehearsal mistress for Brian Macdonald’s _Newcomers_ and Rudolf Nureyev’s _Sleeping Beauty_.

**Comment by rsryman** [comment]
Good to go. This item can be closed, yes?
