### ISSUE TITLE
Resources for Book 4

### ISSUE THREAD

**Issue by rryman** [rryman/BeneshForBalletBook4#9]
Dance 341 - Notation files
[D341L1.pdf](https://github.com/rryman/BeneshForBalletBook4/files/726707/D341L1.pdf)
[D341L2.pdf](https://github.com/rryman/BeneshForBalletBook4/files/726708/D341L2.pdf)
[D341L3.pdf](https://github.com/rryman/BeneshForBalletBook4/files/726709/D341L3.pdf)

**Comment by rryman** [comment]
BenTap - Locations document
[Location_BenTAP.pdf](https://github.com/rryman/BeneshForBalletBook4/files/726726/Location_BenTAP.pdf)

**Comment by rryman** [comment]
Test for adding links from the Encyclopedia:
http://164.39.188.53/encyclopedia/encyclopedia-glossary/orientation-and-travel/bmn-signs/ebmn_02_06_location/location-1-introduction.aspx

**Comment by rryman** [comment]
OpenBenesh Website Links:
http://www.dancewrite.com/KingdomOfLocations/Interactive_Theory.html
http://www.dancewrite.com/KingdomOfLocations/Theory.html - link to the other pages from here.

**Comment by rsryman** [comment]
OK, I have read what I consider the relevant parts of the Encyclopedia and listed them in the attached chart, as a basis for the Benesh Basics theory sections. I'll await word from you before proceeding.
[iBook4encyc.docx](https://github.com/rryman/BeneshForBalletBook4/files/737586/iBook4encyc.docx)

**Comment by rryman** [comment]
What word do you need from me?

---

**Comment by rsryman** [comment]
I thought you were testing the Stage Location widget. Also you were trying to read D341 notes in Sheepshaver before scanning the printout. In the meantime I could begin creating Benesh Basics based on the Encyclopedia.

**Comment by rryman** [comment]
Sounds like a plan.
--
